/**
 * Installer reference overlay — converge-not-merge, staged swap, atomic per unit.
 *
 * P2-S14 / AC-2.4a, AC-2.4b [DR-05], AC-2.4c, GAP-24, risk P2-g.
 *
 * The overlay converges `{claudeDir}/skills/devflow:git/references/` onto the tree the
 * build generates under `dist/skills/git/references/`. It runs on BOTH the shadow and
 * the canonical skill-install branches: a user who shadows `devflow:git` must still
 * receive the canonical GitHub mechanics (UAC-28 — a release blocker, AC-2.11).
 *
 * Fixtures are staged from the REAL generated references (avoids PF-043: a fixture built
 * from a shape the runtime never produces proves nothing). `requireBuiltReferences()`
 * fails loud with a build hint rather than skipping when `dist/` is absent.
 *
 * HOME safety (avoids PF-060): every test passes an explicit mkdtemp `claudeDir` /
 * `devflowDir` / `referencesTarget`. No test reads or writes the real Claude or Devflow
 * config directories under the user's home, and no test shells out to `dist/cli.js init`.
 *
 * Non-vacuity: every assertion below also pins the POSITIVE outcome — an overlay that
 * did nothing at all would fail these tests, not pass them (avoids PF-018).
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { promises as fs } from 'fs';
import * as os from 'os';
import * as path from 'path';

import {
  installViaFileCopy,
  overlayGeneratedReferences,
  promoteUnitStagingTree,
  type OverlayUnit,
  type Spinner,
} from '../../src/targets/claude-code/installer.js';
import { formatOverlaySummary } from '../../src/cli/commands/init.js';
import { sweepOrphanedReferences, MAX_REFERENCE_SWEEP_DEPTH } from '../../src/core/reference-sweep.js';
import { compiledSkillRefsDir } from '../../src/core/assets.js';
import { expandVariants, generatedReferenceManifest } from '../../src/core/mds-variants.js';

// ---------------------------------------------------------------------------
// Harness
// ---------------------------------------------------------------------------

const REAL_REFS = compiledSkillRefsDir();

const noopSpinner: Spinner = { start() {}, stop() {}, message() {} };

/** POSIX path of a manifest entry under a root, spelled for the host filesystem. */
function abs(root: string, relPath: string): string {
  return path.join(root, ...relPath.split('/'));
}

/**
 * The generated manifest, proven present in the real dist tree.
 *
 * Fails loud with the build command rather than skipping — a suite that silently
 * passes on an unbuilt tree asserts nothing (mirrors requireDistFile's contract).
 */
async function requireBuiltReferences(): Promise<readonly string[]> {
  const manifest = generatedReferenceManifest();
  for (const rel of manifest) {
    try {
      await fs.access(abs(REAL_REFS, rel));
    } catch {
      throw new Error(
        `dist/skills/git/references/${rel} is absent — run \`npm run build\` before this suite.`,
      );
    }
  }
  return manifest;
}

/**
 * Stage a source tree holding every entry of `manifest`, with REAL generated bytes.
 *
 * An entry the GitHub-only build does not produce (a fixture-only provider directory)
 * is staged from a real generated reference, so even the synthetic units carry a shape
 * the build actually emits (avoids PF-043).
 */
async function stageSource(root: string, manifest: readonly string[]): Promise<void> {
  const donor = abs(REAL_REFS, 'tracker/github/setup-task.md');
  for (const rel of manifest) {
    const dst = abs(root, rel);
    await fs.mkdir(path.dirname(dst), { recursive: true });
    const src = abs(REAL_REFS, rel);
    try {
      await fs.copyFile(src, dst);
    } catch {
      await fs.copyFile(donor, dst);
    }
  }
}

/** Every entry under `dir`, as POSIX paths relative to it; directories end with `/`. */
async function walkTree(dir: string, prefix = ''): Promise<string[]> {
  const out: string[] = [];
  let entries;
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const entry of entries) {
    const rel = prefix === '' ? entry.name : `${prefix}/${entry.name}`;
    if (entry.isDirectory()) {
      out.push(`${rel}/`);
      out.push(...(await walkTree(path.join(dir, entry.name), rel)));
    } else {
      out.push(rel);
    }
  }
  return out.sort();
}

async function exists(p: string): Promise<boolean> {
  return fs.access(p).then(() => true).catch(() => false);
}

/**
 * Whether this process can make a file genuinely unreadable.
 * Root ignores the mode bits, and some filesystems do not honour them either, so the
 * revocation is verified by an actual read before the isolation test runs.
 */
async function canRevokeRead(file: string): Promise<boolean> {
  if (typeof process.getuid === 'function' && process.getuid() === 0) return false;
  await fs.chmod(file, 0o000);
  return fs.readFile(file).then(() => false).catch(() => true);
}

// ---------------------------------------------------------------------------
// The manifest itself — derived, never hand-listed
// ---------------------------------------------------------------------------

describe('generated reference manifest (bidirectional registry doctrine)', () => {
  it('is derived from the build registries, not restated', () => {
    const expanded = expandVariants();
    expect(expanded.ok, 'VARIANT_MODULES must expand cleanly').toBe(true);
    if (!expanded.ok) return;
    expect(generatedReferenceManifest()).toEqual(expanded.value.map(p => p.relPath));
  });

  it('covers both unit shapes — a nested provider directory and the flat cross-cutting set', () => {
    const manifest = generatedReferenceManifest();
    expect(
      manifest.length,
      'a manifest short enough to enumerate by hand makes every convergence assertion vacuous',
    ).toBeGreaterThanOrEqual(13);
    expect(manifest).toContain('tracker/github/setup-task.md');
    expect(manifest).toContain('decision-markers.md');
    expect(manifest.filter(p => p.startsWith('tracker/github/')).length).toBeGreaterThanOrEqual(10);
  });
});

// ---------------------------------------------------------------------------
// AC-2.4a — the overlay is shadow-independent (UAC-28, release blocker)
// ---------------------------------------------------------------------------

describe('reference overlay through installViaFileCopy (AC-2.4a)', () => {
  let claudeDir: string;
  let devflowDir: string;
  let warnings: string[];
  let manifest: readonly string[];

  const installedRefs = (): string => path.join(claudeDir, 'skills', 'devflow:git', 'references');

  async function runInstall() {
    return installViaFileCopy({
      plugins: [],
      claudeDir,
      devflowDir,
      skillsMap: new Map([['git', 'devflow-code-review']]),
      agentsMap: new Map(),
      isPartialInstall: false,
      spinner: noopSpinner,
      warn: (msg) => { warnings.push(msg); },
    });
  }

  beforeEach(async () => {
    manifest = await requireBuiltReferences();
    claudeDir = await fs.mkdtemp(path.join(os.tmpdir(), 'devflow-overlay-claude-'));
    devflowDir = await fs.mkdtemp(path.join(os.tmpdir(), 'devflow-overlay-home-'));
    warnings = [];
  });

  afterEach(async () => {
    await fs.rm(claudeDir, { recursive: true, force: true });
    await fs.rm(devflowDir, { recursive: true, force: true });
  });

  it('installs every canonical reference byte-equal to the generated source (canonical branch)', async () => {
    const report = await runInstall();

    for (const rel of manifest) {
      const installed = await fs.readFile(abs(installedRefs(), rel));
      const generated = await fs.readFile(abs(REAL_REFS, rel));
      expect(installed.equals(generated), `${rel} must be byte-equal to the generated source`).toBe(true);
    }
    expect([...report.overlaidRefs].sort()).toEqual([...manifest].sort());
    expect(report.overlayFailures).toEqual([]);
  });

  it('a SHADOWED devflow:git still receives the canonical GitHub references (AC-2.4a, UAC-28)', async () => {
    const shadow = path.join(devflowDir, 'skills', 'git');
    await fs.mkdir(shadow, { recursive: true });
    const sentinel = '# my own git skill\nSHADOW-SENTINEL-AC-2-4A\n';
    await fs.writeFile(path.join(shadow, 'SKILL.md'), sentinel, 'utf-8');

    const report = await runInstall();

    // The shadow is honoured …
    expect(report.shadowedSkills).toContain('git');
    expect(
      await fs.readFile(path.join(claudeDir, 'skills', 'devflow:git', 'SKILL.md'), 'utf-8'),
    ).toBe(sentinel);

    // … and the canonical mechanics still land. This is the release-blocker half.
    for (const rel of manifest.filter(p => p.startsWith('tracker/github/'))) {
      const installed = await fs.readFile(abs(installedRefs(), rel));
      const generated = await fs.readFile(abs(REAL_REFS, rel));
      expect(installed.equals(generated), `shadowed install must carry ${rel}`).toBe(true);
    }
    expect([...report.overlaidRefs].sort()).toEqual([...manifest].sort());
  });

  it('prunes a shadow-injected file under references/tracker/** (AC-2.4c)', async () => {
    const shadow = path.join(devflowDir, 'skills', 'git');
    await fs.mkdir(path.join(shadow, 'references', 'tracker', 'jira'), { recursive: true });
    await fs.writeFile(path.join(shadow, 'SKILL.md'), '# shadowed git\n', 'utf-8');
    const injected = path.join(shadow, 'references', 'tracker', 'jira', 'comment.md');
    await fs.writeFile(injected, '# injected mechanics\n', 'utf-8');

    const report = await runInstall();

    expect(
      await exists(path.join(installedRefs(), 'tracker', 'jira', 'comment.md')),
      'a shadow-supplied file that is not in the build manifest must be absent after install',
    ).toBe(false);
    expect(
      await exists(path.join(installedRefs(), 'tracker', 'jira')),
      'the orphaned provider directory must be removed, not left empty',
    ).toBe(false);

    // Positive half: the github set is complete and the prune is reported.
    for (const rel of manifest.filter(p => p.startsWith('tracker/github/'))) {
      expect(await exists(abs(installedRefs(), rel)), `${rel} must be present`).toBe(true);
    }
    expect(report.sweptOrphans.some(o => o.kind === 'reference')).toBe(true);
  });

  it('leaves hand-authored references from the skill source untouched', async () => {
    await runInstall();
    // github-api.md ships with the git skill and is not in the generated manifest.
    expect(await exists(path.join(installedRefs(), 'github-api.md'))).toBe(true);
    expect(generatedReferenceManifest()).not.toContain('github-api.md');
  });
});

// ---------------------------------------------------------------------------
// GAP-24 — stale prune, symlink skip, mode normalisation (unit level)
// ---------------------------------------------------------------------------

describe('converge-not-merge staged swap (GAP-24)', () => {
  let sourceRoot: string;
  let target: string;
  let warnings: string[];
  let manifest: readonly string[];

  const EXTRA_PROVIDER_MANIFEST = ['tracker/jira/comment.md', 'tracker/jira/transition.md'] as const;

  beforeEach(async () => {
    manifest = await requireBuiltReferences();
    sourceRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'devflow-overlay-src-'));
    target = await fs.mkdtemp(path.join(os.tmpdir(), 'devflow-overlay-dst-'));
    warnings = [];
  });

  afterEach(async () => {
    await fs.rm(sourceRoot, { recursive: true, force: true });
    await fs.rm(target, { recursive: true, force: true });
  });

  it('stale-reference prune: a provider directory the manifest no longer lists is removed', async () => {
    const wide = [...manifest, ...EXTRA_PROVIDER_MANIFEST];
    await stageSource(sourceRoot, wide);

    const first = await overlayGeneratedReferences({
      referencesTarget: target,
      sourceRoot,
      manifest: wide,
      warn: (m) => warnings.push(m),
    });
    expect(first.overlayFailures).toEqual([]);
    expect(
      await exists(path.join(target, 'tracker', 'jira', 'comment.md')),
      'the wide manifest must actually install the extra provider first',
    ).toBe(true);

    const second = await overlayGeneratedReferences({
      referencesTarget: target,
      sourceRoot,
      manifest,
      warn: (m) => warnings.push(m),
    });

    expect(await exists(path.join(target, 'tracker', 'jira'))).toBe(false);
    expect(
      second.pruned.scanned,
      'a prune that scanned nothing proves nothing (avoids PF-018)',
    ).toBeGreaterThan(0);
    expect(second.pruned.removed).toContain('jira');
    // Positive half: the retained set survived the prune.
    for (const rel of manifest.filter(p => p.startsWith('tracker/github/'))) {
      expect(await exists(abs(target, rel)), `${rel} must survive the prune`).toBe(true);
    }
  });

  it('skips a symlink entry in the source with a warning and never follows it', async () => {
    await stageSource(sourceRoot, manifest);
    const outside = path.join(sourceRoot, 'outside-the-tree');
    await fs.mkdir(outside, { recursive: true });
    await fs.writeFile(path.join(outside, 'smuggled.md'), '# smuggled\n', 'utf-8');
    await fs.symlink(outside, path.join(sourceRoot, 'tracker', 'github', 'linked'), 'dir');

    const result = await overlayGeneratedReferences({
      referencesTarget: target,
      sourceRoot,
      manifest,
      warn: (m) => warnings.push(m),
    });

    expect(result.overlayFailures).toEqual([]);
    expect([...result.overlaidRefs].sort()).toEqual([...manifest].sort());
    expect(warnings.some(w => w.includes('symlink'))).toBe(true);
    expect(await exists(path.join(target, 'tracker', 'github', 'linked'))).toBe(false);
    expect(await exists(path.join(target, 'tracker', 'github', 'smuggled.md'))).toBe(false);
  });

  it('normalises every installed reference to 0644', async () => {
    await stageSource(sourceRoot, manifest);
    await fs.chmod(abs(sourceRoot, 'tracker/github/setup-task.md'), 0o600);

    await overlayGeneratedReferences({ referencesTarget: target, sourceRoot, manifest });

    const files = (await walkTree(target)).filter(p => !p.endsWith('/'));
    expect(files.length, 'no files installed — the mode assertion would be vacuous').toBeGreaterThanOrEqual(13);
    for (const rel of files) {
      const stat = await fs.stat(abs(target, rel));
      expect(stat.mode & 0o777, `${rel} must be normalised to 0644`).toBe(0o644);
    }
  });
});

// ---------------------------------------------------------------------------
// AC-2.4b [DR-05] — the provider directory is ATOMIC
// ---------------------------------------------------------------------------

describe('atomic per-unit swap (AC-2.4b, DR-05, risk P2-g)', () => {
  let sourceRoot: string;
  let target: string;
  let manifest: readonly string[];
  let wide: string[];

  beforeEach(async () => {
    manifest = await requireBuiltReferences();
    wide = [...manifest, 'tracker/jira/comment.md', 'tracker/jira/transition.md'];
    sourceRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'devflow-overlay-src-'));
    target = await fs.mkdtemp(path.join(os.tmpdir(), 'devflow-overlay-dst-'));
    await stageSource(sourceRoot, wide);
  });

  afterEach(async () => {
    await fs.chmod(abs(sourceRoot, 'tracker/jira/comment.md'), 0o644).catch(() => undefined);
    await fs.rm(sourceRoot, { recursive: true, force: true });
    await fs.rm(target, { recursive: true, force: true });
  });

  it('one unreadable file leaves that provider byte-unchanged and installs the others', async (ctx) => {
    const first = await overlayGeneratedReferences({ referencesTarget: target, sourceRoot, manifest: wide });
    expect(first.overlayFailures, 'the seeding install must succeed').toEqual([]);

    const jiraBefore = await Promise.all(
      ['tracker/jira/comment.md', 'tracker/jira/transition.md'].map(rel => fs.readFile(abs(target, rel))),
    );

    const revoked = await canRevokeRead(abs(sourceRoot, 'tracker/jira/comment.md'));
    if (!revoked) {
      // Running as root, or a filesystem that ignores mode bits: the premise of the
      // test cannot be established, so asserting on it would be theatre. Report it
      // as SKIPPED via vitest's ctx.skip() — a bare `return` here masked an
      // unestablished premise as a PASS, the PF-018 vacuous-green shape.
      ctx.skip();
      return;
    }

    // Mutate the github source so a no-op overlay is distinguishable from a real one.
    await fs.appendFile(abs(sourceRoot, 'tracker/github/setup-task.md'), '\n<!-- second pass -->\n');

    const second = await overlayGeneratedReferences({ referencesTarget: target, sourceRoot, manifest: wide });

    // 1. the failing unit is named, and the install still succeeds (no throw)
    expect(second.overlayFailures.map(f => f.provider)).toEqual(['jira']);
    expect(second.overlayFailures[0].error.length).toBeGreaterThan(0);

    // 2. the pre-existing provider tree is byte-unchanged — never a partial promotion
    const jiraAfter = await Promise.all(
      ['tracker/jira/comment.md', 'tracker/jira/transition.md'].map(rel => fs.readFile(abs(target, rel))),
    );
    expect(jiraAfter[0].equals(jiraBefore[0])).toBe(true);
    expect(jiraAfter[1].equals(jiraBefore[1])).toBe(true);

    // 3. the healthy unit installed normally (positive outcome)
    const installed = await fs.readFile(abs(target, 'tracker/github/setup-task.md'), 'utf-8');
    expect(installed).toContain('<!-- second pass -->');
    expect(second.overlaidRefs).toContain('tracker/github/setup-task.md');
    expect(second.overlaidRefs).not.toContain('tracker/jira/comment.md');

    // 4. no staging residue survives a failed unit
    const residue = (await walkTree(target)).filter(p => p.includes('.tmp'));
    expect(residue, 'a failed unit must leave no .tmp tree behind').toEqual([]);

    // 5. the failure reaches a render site (PF-015)
    const lines = formatOverlaySummary({
      overlaidRefs: second.overlaidRefs,
      overlayFailures: second.overlayFailures,
    });
    expect(lines.some(l => l.level === 'warn' && l.message.includes('jira'))).toBe(true);
  });

  it('a successful provider swap leaves no .old or .tmp residue behind', async () => {
    const result = await overlayGeneratedReferences({ referencesTarget: target, sourceRoot, manifest: wide });
    expect(result.overlayFailures, 'the swap must succeed for this assertion to mean anything').toEqual([]);

    // The promotion displaces the installed unit to a `.old` sibling before renaming
    // the staging tree over it, so the backup has to be dropped on the way out. A
    // surviving `.old` would be installed prose sitting beside the references the
    // agent reads, and — unlike `.tmp` — it holds a full previous copy.
    const residue = (await walkTree(target)).filter(p => p.includes('.old') || p.includes('.tmp'));
    expect(residue, 'a completed swap must leave neither backup nor staging residue').toEqual([]);
    // Positive outcome: the swap actually happened (avoids PF-018).
    expect(result.overlaidRefs).toContain('tracker/github/setup-task.md');
  });

  it('a promotion that fails after displacing the unit restores it instead of deleting it', async () => {
    const first = await overlayGeneratedReferences({ referencesTarget: target, sourceRoot, manifest: wide });
    expect(first.overlayFailures, 'the seeding install must succeed').toEqual([]);

    const unit: OverlayUnit = {
      id: 'jira',
      subdir: 'tracker/jira',
      files: ['tracker/jira/comment.md', 'tracker/jira/transition.md'],
    };
    const before = await Promise.all(unit.files.map(rel => fs.readFile(abs(target, rel))));

    // An ABSENT staging tree is the injectable stand-in for any rename that fails once
    // the installed unit has already been moved aside — the window a rm-then-rename
    // promotion cannot survive, because by then it has deleted the only copy. Driving
    // the real promotion step is what makes this a known-bad probe rather than a
    // restatement of the implementation (PF-018).
    const missingStaging = abs(target, 'tracker/jira') + '.tmp';
    expect(await exists(missingStaging), 'the staging tree must be absent for this probe').toBe(false);

    const promoted = await promoteUnitStagingTree(unit, target, missingStaging);

    expect(promoted.ok, 'promoting an absent staging tree must be reported, never silently ok').toBe(false);

    // The property: the previously installed mechanics are still there, byte for byte.
    // This is precisely what formatOverlaySummary's warning line tells the user, so it
    // is what has to be true.
    const after = await Promise.all(unit.files.map(rel => fs.readFile(abs(target, rel))));
    expect(
      after[0].equals(before[0]) && after[1].equals(before[1]),
      'a failed promotion must restore the displaced unit — leaving the provider empty ' +
      'would strip the agent of every mechanics file while the report claims nothing changed',
    ).toBe(true);

    // …and the backup it used is not left parked beside the live references.
    const residue = (await walkTree(target)).filter(p => p.includes('.old') || p.includes('.tmp'));
    expect(residue, 'a failed promotion must leave neither backup nor staging residue').toEqual([]);
  });

  it('an absent canonical GitHub reference fails loud with a build hint (AC-2.4b)', async () => {
    await fs.rm(abs(sourceRoot, 'tracker/github/setup-task.md'));

    await expect(
      overlayGeneratedReferences({ referencesTarget: target, sourceRoot, manifest: wide }),
    ).rejects.toThrow(/tracker\/github\/setup-task\.md/);
    await expect(
      overlayGeneratedReferences({ referencesTarget: target, sourceRoot, manifest: wide }),
    ).rejects.toThrow(/npm run build:mds/);
  });

  it('an absent cross-cutting document fails loud the same way', async () => {
    await fs.rm(abs(sourceRoot, 'decision-markers.md'));
    await expect(
      overlayGeneratedReferences({ referencesTarget: target, sourceRoot, manifest: wide }),
    ).rejects.toThrow(/decision-markers\.md[\s\S]*npm run build:mds/);
  });
});

// ---------------------------------------------------------------------------
// Render site — a report field with no render site is not a report (PF-015)
// ---------------------------------------------------------------------------

describe('formatOverlaySummary render site (PF-015)', () => {
  it('renders nothing when the overlay did nothing and failed at nothing', () => {
    expect(formatOverlaySummary({ overlaidRefs: [], overlayFailures: [] })).toEqual([]);
  });

  it('reports installed references at info and failed units at warn', () => {
    const lines = formatOverlaySummary({
      overlaidRefs: ['tracker/github/setup-task.md', 'decision-markers.md'],
      overlayFailures: [{ provider: 'jira', error: 'EACCES: permission denied' }],
    });

    const info = lines.filter(l => l.level === 'info');
    const warn = lines.filter(l => l.level === 'warn');
    expect(info).toHaveLength(1);
    expect(info[0].message).toContain('2');
    expect(warn).toHaveLength(1);
    expect(warn[0].message).toContain('jira');
    expect(warn[0].message).toContain('EACCES: permission denied');

    // Exhaustive kinds: every emitted line carries a level the render site handles.
    expect(lines.every(l => l.level === 'info' || l.level === 'warn')).toBe(true);
    expect(lines).toHaveLength(info.length + warn.length);
  });
});

// ---------------------------------------------------------------------------
// Known-bad probes for the path-keyed prune collector
// ---------------------------------------------------------------------------

describe('sweepOrphanedReferences — path-keyed prune collector', () => {
  let root: string;

  beforeEach(async () => {
    root = await fs.mkdtemp(path.join(os.tmpdir(), 'devflow-refsweep-'));
  });

  afterEach(async () => {
    await fs.rm(root, { recursive: true, force: true });
  });

  it('known-bad probe: a seeded file outside the manifest is reported by the same collector', async () => {
    await fs.mkdir(path.join(root, 'github'), { recursive: true });
    await fs.writeFile(path.join(root, 'github', 'setup-task.md'), 'keep\n', 'utf-8');
    await fs.writeFile(path.join(root, 'github', 'smuggled.md'), 'drop\n', 'utf-8');

    const result = await sweepOrphanedReferences(root, new Set(['github/setup-task.md']));

    expect(result.removed).toEqual(['github/smuggled.md']);
    expect(result.scanned).toBeGreaterThan(0);
    expect(await exists(path.join(root, 'github', 'setup-task.md'))).toBe(true);
    expect(await exists(path.join(root, 'github', 'smuggled.md'))).toBe(false);
  });

  it('removes a whole directory no manifest path descends into, and never descends into a retained one', async () => {
    await fs.mkdir(path.join(root, 'github'), { recursive: true });
    await fs.mkdir(path.join(root, 'acme', 'nested'), { recursive: true });
    await fs.writeFile(path.join(root, 'github', 'setup-task.md'), 'keep\n', 'utf-8');
    await fs.writeFile(path.join(root, 'acme', 'nested', 'x.md'), 'drop\n', 'utf-8');

    const result = await sweepOrphanedReferences(root, new Set(['github/setup-task.md']));

    expect(result.removed).toEqual(['acme']);
    expect(await exists(path.join(root, 'acme'))).toBe(false);
    expect(await exists(path.join(root, 'github', 'setup-task.md'))).toBe(true);
    expect(result.failed).toEqual([]);
  });

  it('an absent root is a no-op, not an error (avoids PF-009)', async () => {
    const result = await sweepOrphanedReferences(path.join(root, 'nope'), new Set(['a.md']));
    expect(result).toEqual({ scanned: 0, removed: [], failed: [] });
  });

  // The descent bound is shared with the build's prune (scripts/build-mds.ts) and is
  // breached at `depth > MAX_REFERENCE_SWEEP_DEPTH`, counting the swept root as depth 0.
  // The pair below is a known-bad probe and its in-bounds twin: the same orphan beside
  // the same manifest path, one directory apart. A bound that returned quietly would
  // hand back a result indistinguishable from the converged one (avoids PF-018).
  const nested = (levels: number): string =>
    Array.from({ length: levels }, (_, i) => `d${i + 1}`).join('/');

  async function seedNested(levels: number): Promise<{ known: string; orphan: string }> {
    const dir = nested(levels);
    await fs.mkdir(path.join(root, dir), { recursive: true });
    await fs.writeFile(path.join(root, dir, 'keep.md'), 'keep\n', 'utf-8');
    await fs.writeFile(path.join(root, dir, 'smuggled.md'), 'drop\n', 'utf-8');
    return { known: `${dir}/keep.md`, orphan: `${dir}/smuggled.md` };
  }

  it('sweeps the deepest directory the shared bound permits', async () => {
    const { known, orphan } = await seedNested(MAX_REFERENCE_SWEEP_DEPTH);

    const result = await sweepOrphanedReferences(root, new Set([known]));

    expect(result.removed).toEqual([orphan]);
    expect(result.failed).toEqual([]);
    expect(await exists(path.join(root, orphan))).toBe(false);
    expect(await exists(path.join(root, known))).toBe(true);
  });

  it('known-bad probe: a descent past the bound is reported in failed, not silently truncated', async () => {
    const tooDeep = nested(MAX_REFERENCE_SWEEP_DEPTH + 1);
    const { known, orphan } = await seedNested(MAX_REFERENCE_SWEEP_DEPTH + 1);

    const result = await sweepOrphanedReferences(root, new Set([known]));

    // The subtree genuinely was not swept — the orphan under it survives...
    expect(result.removed).toEqual([]);
    expect(await exists(path.join(root, orphan))).toBe(true);
    // ...and the sweep says so, naming the unvisited directory and the bound it hit,
    // through the same channel the installer already renders (report.sweepFailures).
    expect(result.failed).toHaveLength(1);
    expect(result.failed[0].name).toBe(tooDeep);
    expect(String(result.failed[0].error)).toContain(tooDeep);
    expect(String(result.failed[0].error)).toContain(String(MAX_REFERENCE_SWEEP_DEPTH));
  });
});
