/**
 * Installer reference overlay — converge-not-merge, staged swap, atomic per unit.
 *
 * P2-S14 / AC-2.4a, AC-2.4b [DR-05], AC-2.4c, GAP-24, risk P2-g.
 *
 * The overlay converges `{claudeDir}/skills/devflow:git/references/` onto the tree the
 * build generates under `dist/skills/git/references/`. It runs on BOTH the shadow and
 * the canonical skill-install branches: a user who shadows `devflow:git` must still
 * receive the canonical GitHub mechanics (UAC-28 — a release blocker, AC-2.11).
 *
 * Fixtures are staged from the REAL generated references (avoids PF-043: a fixture built
 * from a shape the runtime never produces proves nothing). `requireBuiltReferences()`
 * fails loud with a build hint rather than skipping when `dist/` is absent.
 *
 * HOME safety (avoids PF-060): every test passes an explicit mkdtemp `claudeDir` /
 * `devflowDir` / `referencesTarget`. No test reads or writes the real Claude or Devflow
 * config directories under the user's home, and no test shells out to `dist/cli.js init`.
 *
 * Non-vacuity: every assertion below also pins the POSITIVE outcome — an overlay that
 * did nothing at all would fail these tests, not pass them (avoids PF-018).
 */

import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { promises as fs } from 'fs';
import * as os from 'os';
import * as path from 'path';

import {
  installViaFileCopy,
  overlayGeneratedReferences,
  planOverlayUnits,
  promoteUnitStagingTree,
  type OverlayFailure,
  type OverlayUnit,
  type Spinner,
} from '../../src/targets/claude-code/installer.js';
import { formatOverlaySummary } from '../../src/cli/commands/install-report.js';
import { sweepOrphanedReferences, MAX_REFERENCE_SWEEP_DEPTH } from '../../src/core/reference-sweep.js';
import { compiledSkillRefsDir } from '../../src/core/assets.js';
import { expandVariants, generatedReferenceManifest, installedReferenceManifest } from '../../src/core/mds-variants.js';

// ---------------------------------------------------------------------------
// Harness
// ---------------------------------------------------------------------------

const REAL_REFS = compiledSkillRefsDir();

const noopSpinner: Spinner = { start() {}, stop() {}, message() {} };

/** POSIX path of a manifest entry under a root, spelled for the host filesystem. */
function abs(root: string, relPath: string): string {
  return path.join(root, ...relPath.split('/'));
}

/**
 * The generated manifest, proven present in the real dist tree.
 *
 * Fails loud with the build command rather than skipping — a suite that silently
 * passes on an unbuilt tree asserts nothing (mirrors requireDistFile's contract).
 */
async function requireBuiltReferences(): Promise<readonly string[]> {
  const manifest = generatedReferenceManifest();
  for (const rel of manifest) {
    try {
      await fs.access(abs(REAL_REFS, rel));
    } catch {
      throw new Error(
        `dist/skills/git/references/${rel} is absent — run \`npm run build\` before this suite.`,
      );
    }
  }
  return manifest;
}

/**
 * Stage a source tree holding every entry of `manifest`, with REAL generated bytes.
 *
 * An entry the GitHub-only build does not produce (a fixture-only provider directory)
 * is staged from a real generated reference, so even the synthetic units carry a shape
 * the build actually emits (avoids PF-043).
 */
async function stageSource(root: string, manifest: readonly string[]): Promise<void> {
  const donor = abs(REAL_REFS, 'tracker/github/setup-task.md');
  for (const rel of manifest) {
    const dst = abs(root, rel);
    await fs.mkdir(path.dirname(dst), { recursive: true });
    const src = abs(REAL_REFS, rel);
    try {
      await fs.copyFile(src, dst);
    } catch {
      await fs.copyFile(donor, dst);
    }
  }
}

/** Every entry under `dir`, as POSIX paths relative to it; directories end with `/`. */
async function walkTree(dir: string, prefix = ''): Promise<string[]> {
  const out: string[] = [];
  let entries;
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const entry of entries) {
    const rel = prefix === '' ? entry.name : `${prefix}/${entry.name}`;
    if (entry.isDirectory()) {
      out.push(`${rel}/`);
      out.push(...(await walkTree(path.join(dir, entry.name), rel)));
    } else {
      out.push(rel);
    }
  }
  return out.sort();
}

async function exists(p: string): Promise<boolean> {
  return fs.access(p).then(() => true).catch(() => false);
}

/**
 * Whether this process can make a file genuinely unreadable.
 * Root ignores the mode bits, and some filesystems do not honour them either, so the
 * revocation is verified by an actual read before the isolation test runs.
 */
async function canRevokeRead(file: string): Promise<boolean> {
  if (typeof process.getuid === 'function' && process.getuid() === 0) return false;
  await fs.chmod(file, 0o000);
  return fs.readFile(file).then(() => false).catch(() => true);
}

// ---------------------------------------------------------------------------
// The manifest itself — derived, never hand-listed
// ---------------------------------------------------------------------------

describe('generated reference manifest (bidirectional registry doctrine)', () => {
  it('is derived from the build registries, not restated', () => {
    const expanded = expandVariants();
    expect(expanded.ok, 'VARIANT_MODULES must expand cleanly').toBe(true);
    if (!expanded.ok) return;
    expect(generatedReferenceManifest()).toEqual(expanded.value.map(p => p.relPath));
  });

  it('covers both unit shapes — a nested provider directory and the flat cross-cutting set', () => {
    const manifest = generatedReferenceManifest();
    expect(
      manifest.length,
      'a manifest short enough to enumerate by hand makes every convergence assertion vacuous',
    ).toBeGreaterThanOrEqual(34);
    expect(manifest).toContain('tracker/github/setup-task.md');
    expect(manifest).toContain('decision-markers.md');
    expect(manifest.filter(p => p.startsWith('tracker/github/')).length).toBeGreaterThanOrEqual(10);
    // The THIRD shape, and the one whose mis-bucketing was a release blocker: a file
    // landing directly in `tracker/`, beside the provider directories rather than
    // inside one. It is a flat set in a subdirectory, not a provider
    // (D-OVERLAY-PROVIDER-SHAPE), and the manifest is where that shape first appears.
    expect(
      manifest.filter(p => p.startsWith('tracker/') && p.split('/').length === 2),
      'no manifest entry lands directly in tracker/ — the unit shape that is neither a provider ' +
      'directory nor a references-root document is unrepresented, and the arms below that cover ' +
      'it are testing nothing',
    ).toEqual(['tracker/_mcp.md']);
  });
});

// ---------------------------------------------------------------------------
// D-OVERLAY-PROVIDER-SHAPE — which KIND of unit a manifest directory becomes
// ---------------------------------------------------------------------------

describe('overlay unit classification (D-OVERLAY-PROVIDER-SHAPE)', () => {
  /**
   * The rule this one replaced: bucket by directory part, then call any non-empty
   * directory part a provider directory.
   *
   * It is here as the known-bad probe. No arm that reads the INSTALLED tree discriminates
   * the two rules — the directory parts sort `'' < tracker < tracker/{provider}`, so a
   * mis-bucketed whole-subtree rename of `tracker/` runs BEFORE the provider units promote
   * back into it and every file is present at the end either way — so the classification
   * is the observation that separates them, and an arm asserting it is only a regression
   * guard if the two rules really disagree on the input it uses (avoids PF-018).
   */
  function shapeBlindKind(subdir: string): OverlayUnit['kind'] {
    return subdir === '' ? 'cross-cutting' : 'provider';
  }

  it('buckets a file landing directly in tracker/ as the flat set there, never as a provider', () => {
    const units = planOverlayUnits([
      'decision-markers.md',
      'tracker/_mcp.md',
      'tracker/github/setup-task.md',
    ]);

    expect(units).toEqual([
      { kind: 'cross-cutting', dir: '', files: ['decision-markers.md'] },
      { kind: 'cross-cutting', dir: 'tracker', files: ['tracker/_mcp.md'] },
      { kind: 'provider', subdir: 'tracker/github', files: ['tracker/github/setup-task.md'] },
    ]);

    // `tracker` is the one directory part the two rules disagree on, which is what makes
    // the assertion above discriminate the defect rather than restate a shape both rules
    // get right. Under the replaced rule that unit is a provider directory, and its atomic
    // swap is a rename of `tracker/` ITSELF over every provider directory beside it.
    expect(
      shapeBlindKind('tracker'),
      'the replaced rule must really classify this differently, or the arm above proves nothing',
    ).toBe('provider');
    expect(shapeBlindKind('tracker/github'), 'the two rules must still agree here').toBe('provider');
    expect(shapeBlindKind(''), 'the two rules must still agree here').toBe('cross-cutting');
  });

  it('classifies the REAL manifest the same way — tracker/ flat, each provider its own unit', async () => {
    const units = planOverlayUnits(await requireBuiltReferences());

    // The synthetic manifest above states the contract; this pins it to the shapes the
    // build actually emits, so neither arm can pass on a shape nothing produces (PF-043).
    expect(
      units.flatMap(u => (u.kind === 'cross-cutting' && u.dir === 'tracker' ? [u.files] : [])),
      'the real manifest carries no flat set in tracker/ — the shape under test is absent',
    ).toEqual([['tracker/_mcp.md']]);

    const flatDirs = units.flatMap(u => (u.kind === 'cross-cutting' ? [u.dir] : []));
    expect(flatDirs, 'the references root is a flat set too').toContain('');

    const providerSubdirs = units.flatMap(u => (u.kind === 'provider' ? [u.subdir] : []));
    expect(
      providerSubdirs.length,
      'no provider unit at all — the discriminating half of this arm would be vacuous',
    ).toBeGreaterThanOrEqual(1);
    for (const subdir of providerSubdirs) {
      expect(
        subdir.split('/'),
        `${subdir} is a provider unit but is not a tracker/{provider} directory`,
      ).toHaveLength(2);
      expect(subdir.startsWith('tracker/'), `${subdir} must live under tracker/`).toBe(true);
    }
    expect(providerSubdirs, 'tracker/ itself is never a provider unit').not.toContain('tracker');
  });
});

// ---------------------------------------------------------------------------
// AC-2.4a — the overlay is shadow-independent (UAC-28, release blocker)
// ---------------------------------------------------------------------------

describe('reference overlay through installViaFileCopy (AC-2.4a)', () => {
  /**
   * The provider this describe installs as — the overlay converges to its set.
   *
   * A tool-call provider rather than github, because its install set is the only
   * one carrying BOTH unit shapes the overlay has to handle: a provider directory
   * (tracker/{provider}/{op}.md) AND a file landing directly in tracker/
   * (tracker/_mcp.md, the flat-set-in-a-subdirectory shape that was once
   * mis-bucketed as a provider directory). It is also a superset of the github
   * set, so the github floor is covered by the same arms.
   */
  const INSTALL_PROVIDER = 'jira';

  let claudeDir: string;
  let devflowDir: string;
  let warnings: string[];
  let manifest: readonly string[];

  const installedRefs = (): string => path.join(claudeDir, 'skills', 'devflow:git', 'references');

  async function runInstall() {
    return installViaFileCopy({
      plugins: [],
      claudeDir,
      devflowDir,
      skillsMap: new Map([['git', 'devflow-code-review']]),
      agentsMap: new Map(),
      trackerProvider: INSTALL_PROVIDER,
      isPartialInstall: false,
      spinner: noopSpinner,
      warn: (msg) => { warnings.push(msg); },
    });
  }

  beforeEach(async () => {
    // The install is provider-scoped: `installViaFileCopy` converges to
    // {github} ∪ {selected provider}, not to everything the build emitted. The
    // built-tree probe still runs, so an unbuilt dist/ fails loud rather than
    // asserting over an empty set.
    await requireBuiltReferences();
    manifest = installedReferenceManifest({ provider: INSTALL_PROVIDER });
    claudeDir = await fs.mkdtemp(path.join(os.tmpdir(), 'devflow-overlay-claude-'));
    devflowDir = await fs.mkdtemp(path.join(os.tmpdir(), 'devflow-overlay-home-'));
    warnings = [];
  });

  afterEach(async () => {
    await fs.rm(claudeDir, { recursive: true, force: true });
    await fs.rm(devflowDir, { recursive: true, force: true });
  });

  it('installs every canonical reference byte-equal to the generated source (canonical branch)', async () => {
    const report = await runInstall();

    for (const rel of manifest) {
      const installed = await fs.readFile(abs(installedRefs(), rel));
      const generated = await fs.readFile(abs(REAL_REFS, rel));
      expect(installed.equals(generated), `${rel} must be byte-equal to the generated source`).toBe(true);
    }
    expect([...report.overlaidRefs].sort()).toEqual([...manifest].sort());
    expect(report.overlayFailures).toEqual([]);
  });

  it('a SHADOWED devflow:git still receives the canonical GitHub references (AC-2.4a, UAC-28)', async () => {
    const shadow = path.join(devflowDir, 'skills', 'git');
    await fs.mkdir(shadow, { recursive: true });
    const sentinel = '# my own git skill\nSHADOW-SENTINEL-AC-2-4A\n';
    await fs.writeFile(path.join(shadow, 'SKILL.md'), sentinel, 'utf-8');

    const report = await runInstall();

    // The shadow is honoured …
    expect(report.shadowedSkills).toContain('git');
    expect(
      await fs.readFile(path.join(claudeDir, 'skills', 'devflow:git', 'SKILL.md'), 'utf-8'),
    ).toBe(sentinel);

    // … and the canonical mechanics still land. This is the release-blocker half.
    //
    // Scoped to EVERY manifest entry under `tracker/`, not only the github ones. The
    // narrower loop passed while a file landing directly in `tracker/` was bucketed as
    // a provider directory named `tracker` — a unit whose atomic swap renames the whole
    // subtree over the provider directories beside it (D-OVERLAY-PROVIDER-SHAPE). The
    // github files survived that by promotion order alone, so a github-only loop is
    // green for a manifest shape the overlay cannot install.
    const trackerRefs = manifest.filter(p => p.startsWith('tracker/'));
    expect(
      trackerRefs.length,
      'the manifest carries no tracker reference — run `npm run build`',
    ).toBeGreaterThan(0);
    for (const rel of trackerRefs) {
      const installed = await fs.readFile(abs(installedRefs(), rel));
      const generated = await fs.readFile(abs(REAL_REFS, rel));
      expect(installed.equals(generated), `shadowed install must carry ${rel}`).toBe(true);
    }
    // And the two shapes are both really present, or the widening above proves nothing:
    // a provider directory and a file landing directly in `tracker/`.
    expect(
      trackerRefs.some(rel => rel.split('/').length === 3),
      'no tracker/{provider}/{op}.md entry — the provider-unit arm is untested here',
    ).toBe(true);
    expect(
      trackerRefs.some(rel => rel.split('/').length === 2),
      'no file landing directly in tracker/ — the flat-set-in-a-subdirectory arm, the one that ' +
      'was mis-bucketed as a provider directory, is untested here',
    ).toBe(true);
    expect([...report.overlaidRefs].sort()).toEqual([...manifest].sort());
  });

  it('prunes a shadow-injected file under references/tracker/** (AC-2.4c)', async () => {
    const shadow = path.join(devflowDir, 'skills', 'git');
    await fs.mkdir(path.join(shadow, 'references', 'tracker', 'probe-provider'), { recursive: true });
    await fs.writeFile(path.join(shadow, 'SKILL.md'), '# shadowed git\n', 'utf-8');
    const injected = path.join(shadow, 'references', 'tracker', 'probe-provider', 'comment.md');
    await fs.writeFile(injected, '# injected mechanics\n', 'utf-8');

    const report = await runInstall();

    expect(
      await exists(path.join(installedRefs(), 'tracker', 'probe-provider', 'comment.md')),
      'a shadow-supplied file that is not in the build manifest must be absent after install',
    ).toBe(false);
    expect(
      await exists(path.join(installedRefs(), 'tracker', 'probe-provider')),
      'the orphaned provider directory must be removed, not left empty',
    ).toBe(false);

    // Positive half: the github set is complete and the prune is reported.
    for (const rel of manifest.filter(p => p.startsWith('tracker/github/'))) {
      expect(await exists(abs(installedRefs(), rel)), `${rel} must be present`).toBe(true);
    }
    expect(report.sweptOrphans.some(o => o.kind === 'reference')).toBe(true);
  });

  it('leaves hand-authored references from the skill source untouched', async () => {
    await runInstall();
    // github-api.md ships with the git skill and is not in the generated manifest.
    expect(await exists(path.join(installedRefs(), 'github-api.md'))).toBe(true);
    expect(generatedReferenceManifest()).not.toContain('github-api.md');
  });
});

// ---------------------------------------------------------------------------
// GAP-24 — stale prune, symlink skip, mode normalisation (unit level)
// ---------------------------------------------------------------------------

describe('converge-not-merge staged swap (GAP-24)', () => {
  let sourceRoot: string;
  let target: string;
  let warnings: string[];
  let manifest: readonly string[];

  /**
   * A provider directory the REAL manifest does not list — the subject of every
   * stale-prune, atomic-swap and isolation arm below.
   *
   * The name is deliberately synthetic. This suite previously used `jira`, which
   * was a provider nothing registered and then became one: the prune arms inverted
   * silently from "the orphan is removed" to "the real provider survives", which is
   * the correct behaviour reported as a failure. `probe-provider` can never be a
   * real provider, and the guard below asserts that rather than trusting it — so if
   * a future provider ever claims the name, this fails with a message saying to
   * pick another instead of quietly testing the opposite property.
   */
  const EXTRA_PROVIDER_MANIFEST = ['tracker/probe-provider/comment.md', 'tracker/probe-provider/transition.md'] as const;

  it('the fixture provider is not a real one — the prune arms have a genuine orphan', () => {
    const real = generatedReferenceManifest();
    for (const rel of EXTRA_PROVIDER_MANIFEST) {
      expect(
        real,
        `${rel} is in the real generated manifest, so it is NOT an orphan and every arm below ` +
        `that expects it to be pruned is asserting the opposite of the shipped behaviour. Pick a ` +
        `fixture provider name no module will ever register.`,
      ).not.toContain(rel);
    }
    expect(
      real.some(rel => rel.startsWith('tracker/')),
      'the real manifest carries no provider directory at all — run `npm run build`',
    ).toBe(true);
  });

  beforeEach(async () => {
    manifest = await requireBuiltReferences();
    sourceRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'devflow-overlay-src-'));
    target = await fs.mkdtemp(path.join(os.tmpdir(), 'devflow-overlay-dst-'));
    warnings = [];
  });

  afterEach(async () => {
    await fs.rm(sourceRoot, { recursive: true, force: true });
    await fs.rm(target, { recursive: true, force: true });
  });

  it('stale-reference prune: a provider directory the manifest no longer lists is removed', async () => {
    const wide = [...manifest, ...EXTRA_PROVIDER_MANIFEST];
    await stageSource(sourceRoot, wide);

    const first = await overlayGeneratedReferences({
      referencesTarget: target,
      sourceRoot,
      manifest: wide,
      warn: (m) => warnings.push(m),
    });
    expect(first.overlayFailures).toEqual([]);
    expect(
      await exists(path.join(target, 'tracker', 'probe-provider', 'comment.md')),
      'the wide manifest must actually install the extra provider first',
    ).toBe(true);

    const second = await overlayGeneratedReferences({
      referencesTarget: target,
      sourceRoot,
      manifest,
      warn: (m) => warnings.push(m),
    });

    expect(await exists(path.join(target, 'tracker', 'probe-provider'))).toBe(false);
    expect(
      second.pruned.scanned,
      'a prune that scanned nothing proves nothing (avoids PF-018)',
    ).toBeGreaterThan(0);
    expect(second.pruned.removed).toContain('probe-provider');
    // Positive half: the retained set survived the prune.
    for (const rel of manifest.filter(p => p.startsWith('tracker/github/'))) {
      expect(await exists(abs(target, rel)), `${rel} must survive the prune`).toBe(true);
    }
  });

  it('skips a symlink entry in the source with a warning and never follows it', async () => {
    await stageSource(sourceRoot, manifest);
    const outside = path.join(sourceRoot, 'outside-the-tree');
    await fs.mkdir(outside, { recursive: true });
    await fs.writeFile(path.join(outside, 'smuggled.md'), '# smuggled\n', 'utf-8');
    await fs.symlink(outside, path.join(sourceRoot, 'tracker', 'github', 'linked'), 'dir');

    const result = await overlayGeneratedReferences({
      referencesTarget: target,
      sourceRoot,
      manifest,
      warn: (m) => warnings.push(m),
    });

    expect(result.overlayFailures).toEqual([]);
    expect([...result.overlaidRefs].sort()).toEqual([...manifest].sort());
    expect(warnings.some(w => w.includes('symlink'))).toBe(true);
    expect(await exists(path.join(target, 'tracker', 'github', 'linked'))).toBe(false);
    expect(await exists(path.join(target, 'tracker', 'github', 'smuggled.md'))).toBe(false);
  });

  it('normalises every installed reference to 0644', async () => {
    await stageSource(sourceRoot, manifest);
    await fs.chmod(abs(sourceRoot, 'tracker/github/setup-task.md'), 0o600);

    await overlayGeneratedReferences({ referencesTarget: target, sourceRoot, manifest });

    const files = (await walkTree(target)).filter(p => !p.endsWith('/'));
    expect(files.length, 'no files installed — the mode assertion would be vacuous').toBeGreaterThanOrEqual(34);
    for (const rel of files) {
      const stat = await fs.stat(abs(target, rel));
      expect(stat.mode & 0o777, `${rel} must be normalised to 0644`).toBe(0o644);
    }
  });

  // -------------------------------------------------------------------------
  // Where a unit stages — process-unique, and inside the converged subtree
  // -------------------------------------------------------------------------

  /**
   * Every staging path one overlay run touched, observed at the filesystem boundary.
   *
   * `stagingDirFor` is internal and should stay internal, but WHERE it points is the whole
   * property under test, so it is observed the way the filesystem sees it: the first thing
   * a unit's build does to its staging path is `fs.rm(path, { recursive: true, force: true })`
   * — the pre-clean — so every unit contributes its path here whatever happens afterwards.
   * Same spy seam the restore probe below uses for `fs.rename`.
   */
  async function captureStagingPaths(run: () => Promise<unknown>): Promise<string[]> {
    const realRm = fs.rm.bind(fs);
    const seen: string[] = [];
    const spy = vi.spyOn(fs, 'rm').mockImplementation(async (target_, options) => {
      if (String(target_).endsWith('.tmp')) seen.push(String(target_));
      return realRm(target_, options);
    });
    try {
      await run();
    } finally {
      spy.mockRestore();
    }
    return [...new Set(seen)];
  }

  it('stages every unit under a process-unique name inside the converged subtree', async () => {
    await stageSource(sourceRoot, manifest);

    const staged = await captureStagingPaths(() => overlayGeneratedReferences({
      referencesTarget: target, sourceRoot, manifest, warn: (m) => warnings.push(m),
    }));

    expect(
      staged.length,
      'no staging path was observed — every assertion below would be vacuous (PF-018)',
    ).toBeGreaterThanOrEqual(2);

    const trackerRoot = path.join(target, 'tracker');
    for (const staging of staged) {
      // security-08. A fixed basename is what let two concurrent `devflow init` runs
      // pre-clean each other's half-built tree and promote whatever survived.
      expect(
        path.basename(staging),
        `${staging} must carry this process's id — a shared name is a shared staging tree`,
      ).toContain(String(process.pid));
      // reliability-08. Whatever a crash strands has to land where the prune will find it.
      // A MIS-BUCKETED unit shows up here too: a file landing directly in `tracker/`
      // bucketed as a provider directory stages at `{target}/tracker.{token}.tmp`, a
      // SIBLING of the converged subtree rather than a path inside it. Which kind each
      // directory classifies as is pinned directly by the D-OVERLAY-PROVIDER-SHAPE arms
      // above; this one is about where a staging tree lands, whichever kind produced it.
      expect(
        staging.startsWith(trackerRoot + path.sep),
        `${staging} must stage under ${trackerRoot}, the only subtree this module converges`,
      ).toBe(true);
    }

    // The flat set is the arm with no installed directory to hang a staging suffix on, so
    // its presence is what makes the loop above a check rather than a formality.
    expect(
      staged.some(p => path.basename(p).startsWith('.cross-cutting.')),
      'the cross-cutting unit must be among the staged units',
    ).toBe(true);
  });

  it('a cross-cutting staging tree stranded by a crashed run is pruned by the next overlay', async () => {
    await stageSource(sourceRoot, manifest);

    const staged = await captureStagingPaths(() => overlayGeneratedReferences({
      referencesTarget: target, sourceRoot, manifest, warn: (m) => warnings.push(m),
    }));
    const flatStaging = staged.find(p => path.basename(p).startsWith('.cross-cutting.'));
    expect(flatStaging, 'the flat set must stage somewhere for this probe to mean anything').toBeDefined();
    if (flatStaging === undefined) return;

    // The crash: an earlier run reached `mkdir` and one copied document, then died before
    // promotion. Seeded beside the real staging path rather than at a location this test
    // invented — that directory IS the property. A DIFFERENT token, because the next run's
    // pre-clean only ever looks at its own name, so the prune is what has to reach it.
    const stranded = path.join(path.dirname(flatStaging), '.cross-cutting.99999-crashedrun.tmp');
    const someFlatDoc = manifest.find(p => !p.includes('/'));
    expect(someFlatDoc, 'the manifest must carry a flat document').toBeDefined();
    await fs.mkdir(stranded, { recursive: true });
    await fs.writeFile(path.join(stranded, String(someFlatDoc)), '# half-written\n', 'utf-8');

    const next = await overlayGeneratedReferences({
      referencesTarget: target, sourceRoot, manifest, warn: (m) => warnings.push(m),
    });

    // Proof of RED: staged at `references/.cross-cutting.tmp` the stranded copy sits
    // outside every convergence this module performs, so both assertions fail — the
    // partial copy stays inside the installed skill and the prune never names it.
    expect(
      await exists(stranded),
      'a partial copy of the cross-cutting documents must not survive inside the installed skill',
    ).toBe(false);
    expect(next.pruned.removed, 'and the prune is what removed it')
      .toContain('.cross-cutting.99999-crashedrun.tmp');

    // Positive half: the successful path is unchanged by where staging lives. The source
    // did not move between the two runs, so every unit is reported unchanged rather than
    // re-promoted (AC-23) — the run still STAGED each one, which is what let the prune
    // reach the stranded tree at all.
    expect(next.overlayFailures).toEqual([]);
    expect([...next.unchangedRefs].sort()).toEqual([...manifest].sort());
    expect(next.overlaidRefs, 'nothing drifted, so nothing was rewritten').toEqual([]);
  });

  // -------------------------------------------------------------------------
  // The chmod walk takes the same descent bound as every other walk over this tree
  // -------------------------------------------------------------------------

  const nestedDir = (levels: number): string =>
    Array.from({ length: levels }, (_, i) => `d${i + 1}`).join('/');

  /** A file the overlay does not own, `levels` directories under the references root. */
  async function seedDeepReference(levels: number): Promise<string> {
    const dir = abs(target, nestedDir(levels));
    await fs.mkdir(dir, { recursive: true });
    const file = path.join(dir, 'hand-authored.md');
    await fs.writeFile(file, '# not ours\n', 'utf-8');
    await fs.chmod(file, 0o600);
    return file;
  }

  /** The overlay's mode-normalisation notices — the channel a breach is reported through. */
  const modeWarnings = (): string[] => warnings.filter(w => w.includes('normalise'));

  it('normalises the deepest directory the shared bound permits', async () => {
    await stageSource(sourceRoot, manifest);
    const file = await seedDeepReference(MAX_REFERENCE_SWEEP_DEPTH);

    await overlayGeneratedReferences({
      referencesTarget: target, sourceRoot, manifest, warn: (m) => warnings.push(m),
    });

    expect((await fs.stat(file)).mode & 0o777, 'the last in-bounds level must still be walked').toBe(0o644);
    expect(modeWarnings(), 'an in-bounds tree must not report a breach').toEqual([]);
  });

  it('known-bad probe: a chmod descent past the bound is reported, not silently walked', async () => {
    await stageSource(sourceRoot, manifest);
    const tooDeep = abs(target, nestedDir(MAX_REFERENCE_SWEEP_DEPTH + 1));
    const file = await seedDeepReference(MAX_REFERENCE_SWEEP_DEPTH + 1);

    const result = await overlayGeneratedReferences({
      referencesTarget: target, sourceRoot, manifest, warn: (m) => warnings.push(m),
    });

    // The walk genuinely stopped — the file past the bound keeps the mode it arrived with.
    // (`Dirent.isDirectory()` is lstat-based, so no symlink loop can reach this state; the
    // bound is here so the one unbounded walk over this tree stops holding the opposite
    // position on a hazard its two siblings document.)
    expect((await fs.stat(file)).mode & 0o777, 'a bounded walk must not reach past the bound').toBe(0o600);

    // ...and the run says so, naming the directory and the bound, through the channel the
    // overlay already renders for mode normalisation. A bound that returned quietly would
    // leave this run indistinguishable from one that normalised the whole tree (PF-018).
    const breach = modeWarnings();
    expect(breach, 'a breached bound must be reported exactly once').toHaveLength(1);
    expect(breach[0]).toContain(String(MAX_REFERENCE_SWEEP_DEPTH));
    expect(breach[0]).toContain(tooDeep);

    // Positive half: an install is not abandoned over one unwalked subtree (avoids PF-009).
    expect(result.overlayFailures).toEqual([]);
    expect([...result.overlaidRefs].sort()).toEqual([...manifest].sort());
  });
});

// ---------------------------------------------------------------------------
// AC-2.4b [DR-05] — the provider directory is ATOMIC
// ---------------------------------------------------------------------------

describe('atomic per-unit swap (AC-2.4b, DR-05, risk P2-g)', () => {
  let sourceRoot: string;
  let target: string;
  let manifest: readonly string[];
  let wide: string[];

  beforeEach(async () => {
    manifest = await requireBuiltReferences();
    wide = [...manifest, 'tracker/probe-provider/comment.md', 'tracker/probe-provider/transition.md'];
    sourceRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'devflow-overlay-src-'));
    target = await fs.mkdtemp(path.join(os.tmpdir(), 'devflow-overlay-dst-'));
    await stageSource(sourceRoot, wide);
  });

  afterEach(async () => {
    // The directory first: a 0o000 parent makes the file chmod below fail with EACCES,
    // and then `rm -r` cannot list it either, which would fail the teardown rather than
    // the test that revoked it.
    await fs.chmod(abs(sourceRoot, 'tracker/probe-provider'), 0o755).catch(() => undefined);
    await fs.chmod(abs(sourceRoot, 'tracker/probe-provider/comment.md'), 0o644).catch(() => undefined);
    await fs.rm(sourceRoot, { recursive: true, force: true });
    await fs.rm(target, { recursive: true, force: true });
  });

  it('one unreadable file leaves that provider byte-unchanged and installs the others', async (ctx) => {
    const first = await overlayGeneratedReferences({ referencesTarget: target, sourceRoot, manifest: wide });
    expect(first.overlayFailures, 'the seeding install must succeed').toEqual([]);

    const probeBefore = await Promise.all(
      ['tracker/probe-provider/comment.md', 'tracker/probe-provider/transition.md'].map(rel => fs.readFile(abs(target, rel))),
    );

    const revoked = await canRevokeRead(abs(sourceRoot, 'tracker/probe-provider/comment.md'));
    if (!revoked) {
      // Running as root, or a filesystem that ignores mode bits: the premise of the
      // test cannot be established, so asserting on it would be theatre. Report it
      // as SKIPPED via vitest's ctx.skip() — a bare `return` here masked an
      // unestablished premise as a PASS, the PF-018 vacuous-green shape.
      ctx.skip();
      return;
    }

    // Mutate the github source so a no-op overlay is distinguishable from a real one.
    await fs.appendFile(abs(sourceRoot, 'tracker/github/setup-task.md'), '\n<!-- second pass -->\n');

    const second = await overlayGeneratedReferences({ referencesTarget: target, sourceRoot, manifest: wide });

    // 1. the failing unit is named, and the install still succeeds (no throw)
    expect(second.overlayFailures.map(f => f.unit)).toEqual([
      { kind: 'provider', subdir: 'tracker/probe-provider' },
    ]);
    expect(second.overlayFailures[0].error.length).toBeGreaterThan(0);

    // 1b. …and the state it reports is the one that is actually true here: this unit
    // WAS installed, the build failed before anything was touched, so "left unchanged"
    // is the honest sentence. The other arms of the union are proven separately — the
    // point of the discriminant is that this one is a finding, not a default.
    expect(second.overlayFailures[0].state).toEqual({ kind: 'installed-unchanged' });

    // 2. the pre-existing provider tree is byte-unchanged — never a partial promotion
    const probeAfter = await Promise.all(
      ['tracker/probe-provider/comment.md', 'tracker/probe-provider/transition.md'].map(rel => fs.readFile(abs(target, rel))),
    );
    expect(probeAfter[0].equals(probeBefore[0])).toBe(true);
    expect(probeAfter[1].equals(probeBefore[1])).toBe(true);

    // 3. the healthy unit installed normally (positive outcome)
    const installed = await fs.readFile(abs(target, 'tracker/github/setup-task.md'), 'utf-8');
    expect(installed).toContain('<!-- second pass -->');
    expect(second.overlaidRefs).toContain('tracker/github/setup-task.md');
    expect(second.overlaidRefs).not.toContain('tracker/probe-provider/comment.md');

    // 4. no staging residue survives a failed unit
    const residue = (await walkTree(target)).filter(p => p.includes('.tmp'));
    expect(residue, 'a failed unit must leave no .tmp tree behind').toEqual([]);

    // 5. the failure reaches a render site (PF-015)
    const lines = formatOverlaySummary({
      overlaidRefs: second.overlaidRefs,
      overlayFailures: second.overlayFailures,
    });
    expect(lines.some(l => l.level === 'warn' && l.message.includes('probe-provider'))).toBe(true);
  });

  it('a successful provider swap leaves no .old or .tmp residue behind', async () => {
    const result = await overlayGeneratedReferences({ referencesTarget: target, sourceRoot, manifest: wide });
    expect(result.overlayFailures, 'the swap must succeed for this assertion to mean anything').toEqual([]);

    // The promotion displaces the installed unit to a `.old` sibling before renaming
    // the staging tree over it, so the backup has to be dropped on the way out. A
    // surviving `.old` would be installed prose sitting beside the references the
    // agent reads, and — unlike `.tmp` — it holds a full previous copy.
    const residue = (await walkTree(target)).filter(p => p.includes('.old') || p.includes('.tmp'));
    expect(residue, 'a completed swap must leave neither backup nor staging residue').toEqual([]);
    // Positive outcome: the swap actually happened (avoids PF-018).
    expect(result.overlaidRefs).toContain('tracker/github/setup-task.md');
  });

  it('a promotion that fails after displacing the unit restores it instead of deleting it', async () => {
    const first = await overlayGeneratedReferences({ referencesTarget: target, sourceRoot, manifest: wide });
    expect(first.overlayFailures, 'the seeding install must succeed').toEqual([]);

    const unit: OverlayUnit = {
      kind: 'provider',
      subdir: 'tracker/probe-provider',
      files: ['tracker/probe-provider/comment.md', 'tracker/probe-provider/transition.md'],
    };
    const before = await Promise.all(unit.files.map(rel => fs.readFile(abs(target, rel))));

    // An ABSENT staging tree is the injectable stand-in for any rename that fails once
    // the installed unit has already been moved aside — the window a rm-then-rename
    // promotion cannot survive, because by then it has deleted the only copy. Driving
    // the real promotion step is what makes this a known-bad probe rather than a
    // restatement of the implementation (PF-018).
    const missingStaging = abs(target, 'tracker/probe-provider') + '.tmp';
    expect(await exists(missingStaging), 'the staging tree must be absent for this probe').toBe(false);

    const promoted = await promoteUnitStagingTree(unit, target, missingStaging);

    expect(promoted.ok, 'promoting an absent staging tree must be reported, never silently ok').toBe(false);

    // The restore SUCCEEDED here, which is the one case in which "left unchanged" is a
    // true sentence — so that is the state reported. The probe below it drives the same
    // window with a restore that fails, and must not reach this arm.
    if (!promoted.ok) expect(promoted.state).toEqual({ kind: 'installed-unchanged' });

    // The property: the previously installed mechanics are still there, byte for byte.
    // This is precisely what formatOverlaySummary's warning line tells the user, so it
    // is what has to be true.
    const after = await Promise.all(unit.files.map(rel => fs.readFile(abs(target, rel))));
    expect(
      after[0].equals(before[0]) && after[1].equals(before[1]),
      'a failed promotion must restore the displaced unit — leaving the provider empty ' +
      'would strip the agent of every mechanics file while the report claims nothing changed',
    ).toBe(true);

    // …and the backup it used is not left parked beside the live references.
    const residue = (await walkTree(target)).filter(p => p.includes('.old') || p.includes('.tmp'));
    expect(residue, 'a failed promotion must leave neither backup nor staging residue').toEqual([]);
  });

  it('a unit with no installed copy reports not-installed, never "left unchanged"', async (ctx) => {
    // Nothing is installed yet — `target` is a fresh mkdtemp root. Revoking read on the
    // provider's SOURCE directory fails its build before anything is copied, which is the
    // shape a `build:cli`-only tree produces for every unit at once.
    const probeSource = abs(sourceRoot, 'tracker/probe-provider');
    if (typeof process.getuid === 'function' && process.getuid() === 0) { ctx.skip(); return; }
    await fs.chmod(probeSource, 0o000);
    const revoked = await fs.readdir(probeSource).then(() => false).catch(() => true);
    if (!revoked) { ctx.skip(); return; }

    let result;
    try {
      result = await overlayGeneratedReferences({ referencesTarget: target, sourceRoot, manifest: wide });
    } finally {
      await fs.chmod(probeSource, 0o755).catch(() => undefined);
    }

    // The distinction the state must carry: this unit is not stale, it is ABSENT.
    expect(result.overlayFailures).toHaveLength(1);
    expect(result.overlayFailures[0].unit).toEqual({ kind: 'provider', subdir: 'tracker/probe-provider' });
    expect(result.overlayFailures[0].state).toEqual({
      kind: 'not-installed',
      absent: ['tracker/probe-provider/comment.md', 'tracker/probe-provider/transition.md'],
    });
    for (const rel of ['tracker/probe-provider/comment.md', 'tracker/probe-provider/transition.md']) {
      expect(await exists(abs(target, rel)), `${rel} must really be absent`).toBe(false);
    }

    // Positive half: every other unit installed normally, and no staging residue survives.
    expect(result.overlaidRefs).toContain('tracker/github/setup-task.md');
    expect(result.overlaidRefs).toContain('decision-markers.md');
    expect((await walkTree(target)).filter(p => p.includes('.tmp'))).toEqual([]);

    // …and the render site says "absent", not "unchanged".
    const [line] = formatOverlaySummary({
      overlaidRefs: result.overlaidRefs,
      overlayFailures: result.overlayFailures,
    }).filter(l => l.level === 'warn');
    expect(line.message).toContain('tracker/probe-provider');
    expect(line.message).toContain('absent');
    expect(line.message).not.toContain('left unchanged');
  });

  it('a flat-set promotion caught mid-flight reports which documents are new and which are stale', async () => {
    const seeded = await overlayGeneratedReferences({ referencesTarget: target, sourceRoot, manifest: wide });
    expect(seeded.overlayFailures, 'the seeding install must succeed').toEqual([]);

    // The cross-cutting documents — the unit with no directory to swap back.
    const flat = wide.filter(p => !p.includes('/'));
    expect(flat.length, 'a one-document flat set cannot be caught MID-flight').toBeGreaterThanOrEqual(2);

    // A staging tree holding only the FIRST document: its rename lands, the next one
    // finds nothing to rename. That is precisely the window D-OVERLAY-FLAT-UNIT
    // documents, driven through the real promotion rather than described in a comment.
    // Spelled where the overlay itself stages the flat set — under the converged subtree,
    // with a per-run token — so this probe does not preserve a location nothing produces.
    // The path is supplied to the promotion directly, so only its shape matters here.
    const staging = path.join(target, 'tracker', `.cross-cutting.${process.pid}-midflight.tmp`);
    await fs.mkdir(staging, { recursive: true });
    await fs.writeFile(path.join(staging, flat[0]), '# refreshed by this run\n', 'utf-8');

    const unit: OverlayUnit = { kind: 'cross-cutting', dir: '', files: flat };
    const promoted = await promoteUnitStagingTree(unit, target, staging);

    expect(promoted.ok, 'a rename over an absent document must be reported').toBe(false);
    if (promoted.ok) return;
    expect(promoted.state).toEqual({
      kind: 'partially-refreshed',
      refreshed: [flat[0]],
      stale: flat.slice(1),
    });

    // The disk agrees with the report: one document is this run's, the rest are not.
    expect(await fs.readFile(abs(target, flat[0]), 'utf-8')).toContain('refreshed by this run');
    for (const rel of flat.slice(1)) {
      const installed = await fs.readFile(abs(target, rel));
      const generated = await fs.readFile(abs(sourceRoot, rel));
      expect(installed.equals(generated), `${rel} must still be the previous install`).toBe(true);
    }

    const [line] = formatOverlaySummary({
      overlaidRefs: [],
      overlayFailures: [{ unit: { kind: 'cross-cutting', dir: '' }, state: promoted.state, error: promoted.error }],
    });
    expect(line.message).toContain('part new and part old');
    expect(line.message).not.toContain('left unchanged');
  });

  it('promotes a flat set into its directory even when that directory does not exist yet', async () => {
    // The two flat directories the registry emits today both exist by the time promotion
    // runs, for reasons that have nothing to do with the unit landing in them: the
    // references root is created by overlayGeneratedReferences, and `tracker/` as a side
    // effect of the flat arm's own staging path. A flat set landing anywhere else has
    // neither, so the promotion has to create the directory it renames into — the same
    // thing promoteProviderUnit does for its target's parent.
    const flatProbeDir = 'shared';
    expect(
      generatedReferenceManifest().some(rel => rel.startsWith(`${flatProbeDir}/`)),
      `${flatProbeDir}/ is a real generated directory now, so it exists before promotion and ` +
      'this probe no longer drives a missing one. Pick a directory the build does not emit.',
    ).toBe(false);

    const unit: OverlayUnit = {
      kind: 'cross-cutting',
      dir: flatProbeDir,
      files: [`${flatProbeDir}/glossary.md`, `${flatProbeDir}/decision-markers.md`],
    };
    // Spelled where the overlay itself stages a flat set — under the converged subtree,
    // with a per-run token — so the probe does not preserve a location nothing produces.
    const staging = path.join(target, 'tracker', `.cross-cutting.${flatProbeDir}.${process.pid}-mkdir.tmp`);
    await fs.mkdir(staging, { recursive: true });
    for (const rel of unit.files) {
      await fs.writeFile(path.join(staging, path.basename(rel)), `# ${rel} from this run\n`, 'utf-8');
    }
    expect(
      await exists(abs(target, flatProbeDir)),
      'the destination directory must be absent, or this probe drives the path that already works',
    ).toBe(false);

    const promoted = await promoteUnitStagingTree(unit, target, staging);

    // Proof of RED: without the mkdir the first rename is ENOENT, the promotion is reported
    // as failed, and not one of the unit's documents reaches the installed skill.
    expect(
      promoted.ok,
      'a flat set must create the directory it renames into rather than depend on another ' +
      'unit having happened to make it',
    ).toBe(true);
    for (const rel of unit.files) {
      expect(await fs.readFile(abs(target, rel), 'utf-8')).toContain(`# ${rel} from this run`);
    }
    // …and it is dropped on the way out, like every other completed promotion.
    expect(await exists(staging), 'a completed promotion must leave no staging residue').toBe(false);
  });

  it('a restore that fails is reported as such, and its recovery copy survives the same run', async () => {
    const seeded = await overlayGeneratedReferences({ referencesTarget: target, sourceRoot, manifest: wide });
    expect(seeded.overlayFailures, 'the seeding install must succeed').toEqual([]);

    const live = abs(target, 'tracker/probe-provider');
    const backup = `${live}.old`;
    const before = await fs.readFile(abs(target, 'tracker/probe-provider/comment.md'));

    // Drift in all three units, because a promotion only runs for a unit that has
    // something to promote: a source identical to what is installed is reported unchanged
    // and never reaches the rename below (AC-23). Read of `before` is above this, so the
    // backup's bytes are still the ones the assertions compare against.
    for (const rel of ['tracker/probe-provider/comment.md', 'tracker/github/setup-task.md', 'decision-markers.md']) {
      await fs.appendFile(abs(sourceRoot, rel), '\n<!-- drifted -->\n');
    }

    // Two renames no filesystem can be coaxed into failing on demand, in this order: the
    // staging rename (so the promotion fails AFTER displacing the unit) and the restore
    // that follows it. Everything else runs for real — the displacement, the `.old`
    // backup, the other two units, the prune. Same seam tests/manifest.test.ts uses for
    // an un-provokable rename failure.
    //
    // Proof of RED: with the restore swallowed by `.catch(() => undefined)` the state is
    // `installed-unchanged` and the prune then removes `tracker/probe-provider.old` in this very
    // run — the backup-survival and prune-report assertions below both fail.
    const realRename = fs.rename.bind(fs);
    // Matched on the unit's own name rather than a literal staging basename: the staging
    // directory carries a per-process token (`probe-provider.<pid>-<t36>.tmp`), so a spy keyed to a
    // fixed `probe-provider.tmp` would silently stop matching and let the promotion succeed.
    const stagingOrBackup = /(^|[/\\])probe-provider(\..+)?\.(tmp|old)$/;
    const renameSpy = vi.spyOn(fs, 'rename').mockImplementation(async (from, to) => {
      if (stagingOrBackup.test(String(from))) {
        throw new Error('EIO: simulated rename failure');
      }
      return realRename(from, to);
    });

    let result;
    try {
      result = await overlayGeneratedReferences({ referencesTarget: target, sourceRoot, manifest: wide });
    } finally {
      renameSpy.mockRestore();
    }

    // 1. the failure names the state it actually left: nothing live, a backup to recover from
    expect(result.overlayFailures).toHaveLength(1);
    expect(result.overlayFailures[0].unit).toEqual({ kind: 'provider', subdir: 'tracker/probe-provider' });
    const state = result.overlayFailures[0].state;
    expect(state.kind).toBe('restore-failed');
    if (state.kind !== 'restore-failed') return;
    expect(state.recoveryPath).toBe(backup);
    expect(state.restoreError).toContain('simulated rename failure');

    // 2. the recovery copy the report names is still there when the run ends — byte for
    //    byte — and the live path is empty, exactly as the state claims.
    expect(await exists(backup), 'the prune must not delete the copy this run is relying on').toBe(true);
    expect((await fs.readFile(path.join(backup, 'comment.md'))).equals(before)).toBe(true);
    expect(await exists(live)).toBe(false);

    // 3. the skipped prune is reported, not silent — nothing claims convergence over
    //    ground it did not cover (PF-009, PF-015).
    expect(result.pruned.removed).toEqual([]);
    expect(result.pruned.failed).toHaveLength(1);
    expect(result.pruned.failed[0].name).toBe('tracker');
    expect(String(result.pruned.failed[0].error)).toContain(backup);

    // 4. positive half: the units that could be promoted were
    expect(result.overlaidRefs).toContain('tracker/github/setup-task.md');
    expect(result.overlaidRefs).toContain('decision-markers.md');

    // 5. and the user is told where the only copy is
    const [line] = formatOverlaySummary({
      overlaidRefs: result.overlaidRefs,
      overlayFailures: result.overlayFailures,
    }).filter(l => l.level === 'warn');
    expect(line.message).toContain(backup);
    expect(line.message).toContain('could NOT be put back');
    expect(line.message).not.toContain('left unchanged');

    // 6. known-bad probe — the exemption is load-bearing, not vacuously satisfied by a
    //    backup the prune would have spared anyway: the SAME prune, over the same root
    //    with the same manifest, takes `probe-provider.old` with it. Destructive by design, and
    //    last: it proves what the skipped prune would have done to the recovery copy.
    const trackerPrefix = `${'tracker'}/`;
    const unguarded = await sweepOrphanedReferences(
      path.join(target, 'tracker'),
      new Set(wide.filter(p => p.startsWith(trackerPrefix)).map(p => p.slice(trackerPrefix.length))),
    );
    expect(unguarded.removed).toContain('probe-provider.old');
    expect(await exists(backup), 'the unguarded prune deletes the only surviving copy').toBe(false);
  });

  it('an absent canonical GitHub reference fails loud with a build hint (AC-2.4b)', async () => {
    await fs.rm(abs(sourceRoot, 'tracker/github/setup-task.md'));

    await expect(
      overlayGeneratedReferences({ referencesTarget: target, sourceRoot, manifest: wide }),
    ).rejects.toThrow(/tracker\/github\/setup-task\.md/);
    await expect(
      overlayGeneratedReferences({ referencesTarget: target, sourceRoot, manifest: wide }),
    ).rejects.toThrow(/npm run build:mds/);
  });

  it('an absent cross-cutting document fails loud the same way', async () => {
    await fs.rm(abs(sourceRoot, 'decision-markers.md'));
    await expect(
      overlayGeneratedReferences({ referencesTarget: target, sourceRoot, manifest: wide }),
    ).rejects.toThrow(/decision-markers\.md[\s\S]*npm run build:mds/);
  });

  /**
   * The `build:cli`-only tree, which is the one shape the per-entry throw above could
   * never see: it is raised after a successful `readdir` of a unit's source directory,
   * and when the whole generated root is absent no unit ever gets that far. Every unit
   * then degrades to a reported failure and the install returns success with an agent
   * whose mechanics pointers resolve to nothing.
   */
  it('an absent generated tree fails loud before anything is installed, naming the build step', async () => {
    const absentRoot = path.join(sourceRoot, 'never-built');
    expect(await exists(absentRoot), 'the probe needs a root that really is not there').toBe(false);

    await expect(
      overlayGeneratedReferences({ referencesTarget: target, sourceRoot: absentRoot, manifest: wide }),
    ).rejects.toThrow(/npm run build:mds/);
    await expect(
      overlayGeneratedReferences({ referencesTarget: target, sourceRoot: absentRoot, manifest: wide }),
    ).rejects.toThrow(absentRoot);

    // The refusal is the whole outcome: no half-built references directory beside it.
    expect(
      (await walkTree(target)).filter(p => !p.endsWith('/')),
      'a refused overlay must install nothing at all',
    ).toEqual([]);

    // Positive half: the SAME call over the staged tree installs the whole manifest, so
    // the refusal is selected by the absent root and not by the arguments around it.
    const healthy = await overlayGeneratedReferences({ referencesTarget: target, sourceRoot, manifest: wide });
    expect(healthy.overlayFailures).toEqual([]);
    expect([...healthy.overlaidRefs].sort()).toEqual([...wide].sort());
  });

  it('known-bad probe: one absent unit directory under a present root is reported, never thrown', async () => {
    // The boundary the whole-tree refusal must not cross. Hoisting that `stat` into the
    // unit loop passes the probe above and fails this one: a single unbuilt provider
    // would abort the entire install, which is the blast radius PF-009 exists to keep
    // out of this path. The root is present here; exactly one unit's directory is not.
    await fs.rm(abs(sourceRoot, 'tracker/probe-provider'), { recursive: true });

    const result = await overlayGeneratedReferences({ referencesTarget: target, sourceRoot, manifest: wide });

    expect(result.overlayFailures).toHaveLength(1);
    expect(result.overlayFailures[0].unit).toEqual({ kind: 'provider', subdir: 'tracker/probe-provider' });
    expect(result.overlayFailures[0].state).toEqual({
      kind: 'not-installed',
      absent: ['tracker/probe-provider/comment.md', 'tracker/probe-provider/transition.md'],
    });

    // …and every other unit installed: a degradation, not an abort.
    expect(result.overlaidRefs).toContain('tracker/github/setup-task.md');
    expect(result.overlaidRefs).toContain('decision-markers.md');
    expect((await walkTree(target)).filter(p => p.includes('.tmp'))).toEqual([]);
  });
});

// ---------------------------------------------------------------------------
// AC-23 — a unit already installed byte-for-byte is REPORTED, never rewritten
// ---------------------------------------------------------------------------

describe('unchanged units are reported separately (AC-23)', () => {
  let sourceRoot: string;
  let target: string;
  let manifest: readonly string[];

  beforeEach(async () => {
    manifest = await requireBuiltReferences();
    sourceRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'devflow-overlay-src-'));
    target = await fs.mkdtemp(path.join(os.tmpdir(), 'devflow-overlay-dst-'));
    await stageSource(sourceRoot, manifest);
  });

  afterEach(async () => {
    await fs.rm(sourceRoot, { recursive: true, force: true });
    await fs.rm(target, { recursive: true, force: true });
  });

  const overlay = (): ReturnType<typeof overlayGeneratedReferences> =>
    overlayGeneratedReferences({ referencesTarget: target, sourceRoot, manifest });

  /**
   * Inode per manifest entry — what separates "did not write" from "wrote the same bytes".
   *
   * Every promotion path installs a file by renaming a freshly COPIED staging entry into
   * place, so a re-promoted document always arrives with a new inode even when its bytes
   * are identical. The report alone would be a label; this is the observation behind it
   * (avoids PF-018).
   */
  const inodes = (): Promise<number[]> =>
    Promise.all(manifest.map(async rel => (await fs.stat(abs(target, rel))).ino));

  it('a repeat overlay over an identical source writes nothing and reports every unit unchanged', async () => {
    const first = await overlay();
    expect(first.overlayFailures).toEqual([]);
    expect(
      [...first.overlaidRefs].sort(),
      'the seeding run must really install the whole manifest',
    ).toEqual([...manifest].sort());
    expect(first.unchangedRefs, 'nothing was installed before it, so nothing can be unchanged').toEqual([]);

    const before = await inodes();

    const second = await overlay();

    expect(second.overlayFailures).toEqual([]);
    expect(
      second.overlaidRefs,
      'nothing was written, so nothing may be reported as installed — this is the whole of ' +
      'what makes `tracker --set <same provider>` able to say (unchanged)',
    ).toEqual([]);
    expect([...second.unchangedRefs].sort()).toEqual([...manifest].sort());
    expect(await inodes(), 'an unchanged unit must not be re-promoted on disk').toEqual(before);

    // …and the render site says nothing at all, rather than "Installed N references".
    expect(formatOverlaySummary({
      overlaidRefs: second.overlaidRefs,
      overlayFailures: second.overlayFailures,
    })).toEqual([]);
  });

  it('known-bad probe: a byte-changed source file IS re-promoted, and only its own unit', async () => {
    await overlay();

    const changed = 'tracker/github/setup-task.md';
    await fs.appendFile(abs(sourceRoot, changed), '\n<!-- drifted -->\n');

    const result = await overlay();

    expect(result.overlayFailures).toEqual([]);
    expect(result.overlaidRefs, 'drift must never hide behind an unchanged report').toContain(changed);
    expect(result.unchangedRefs).not.toContain(changed);
    expect(
      await fs.readFile(abs(target, changed), 'utf-8'),
      'and the drifted bytes are the ones now installed',
    ).toContain('<!-- drifted -->');

    // Only that unit moved. Every entry outside `tracker/github/` is still unchanged, so
    // an implementation that gave up and re-promoted everything would fail here too.
    const others = manifest.filter(rel => !rel.startsWith('tracker/github/'));
    expect(
      others.length,
      'the manifest carries only one unit — the per-unit half of this probe is vacuous',
    ).toBeGreaterThan(0);
    for (const rel of others) {
      expect(result.unchangedRefs, `${rel} did not change and must not be re-promoted`).toContain(rel);
    }
  });

  it('a provider directory holding a file the manifest does not name is NOT unchanged', async () => {
    await overlay();

    // A provider unit is swapped WHOLE, so this stray is something the promotion removes.
    // A comparison over the manifest's own files alone would call the unit unchanged and
    // leave the stray installed — convergence silently downgraded to a merge.
    const stray = abs(target, 'tracker/github/stray-op.md');
    await fs.writeFile(stray, '# left by an earlier build\n', 'utf-8');

    const result = await overlay();

    expect(result.overlaidRefs).toContain('tracker/github/setup-task.md');
    expect(result.unchangedRefs).not.toContain('tracker/github/setup-task.md');
    expect(
      await exists(stray),
      'the whole-directory swap must still remove what the manifest does not name',
    ).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// Render site — a report field with no render site is not a report (PF-015)
// ---------------------------------------------------------------------------

describe('formatOverlaySummary render site (PF-015)', () => {
  it('renders nothing when the overlay did nothing and failed at nothing', () => {
    expect(formatOverlaySummary({ overlaidRefs: [], overlayFailures: [] })).toEqual([]);
  });

  it('reports installed references at info and failed units at warn', () => {
    const lines = formatOverlaySummary({
      overlaidRefs: ['tracker/github/setup-task.md', 'decision-markers.md'],
      overlayFailures: [{
        unit: { kind: 'provider', subdir: 'tracker/probe-provider' },
        state: { kind: 'installed-unchanged' },
        error: 'EACCES: permission denied',
      }],
    });

    const info = lines.filter(l => l.level === 'info');
    const warn = lines.filter(l => l.level === 'warn');
    expect(info).toHaveLength(1);
    expect(info[0].message).toContain('2');
    expect(warn).toHaveLength(1);
    expect(warn[0].message).toContain('tracker/probe-provider');
    expect(warn[0].message).toContain('EACCES: permission denied');

    // Exhaustive kinds: every emitted line carries a level the render site handles.
    expect(lines.every(l => l.level === 'info' || l.level === 'warn')).toBe(true);
    expect(lines).toHaveLength(info.length + warn.length);
  });

  /**
   * One sentence per state, and no two the same. A discriminant whose arms all render
   * identically is the defect this replaced wearing a type — so the assertion is that
   * the four sentences are DISTINCT, not merely that each contains a keyword.
   */
  it('renders a different, state-specific sentence for every OverlayFailureState', () => {
    const failures: OverlayFailure[] = [
      {
        unit: { kind: 'provider', subdir: 'tracker/probe-provider' },
        state: { kind: 'installed-unchanged' },
        error: 'EACCES',
      },
      {
        unit: { kind: 'provider', subdir: 'tracker/probe-provider' },
        state: { kind: 'not-installed', absent: ['tracker/probe-provider/comment.md'] },
        error: 'EACCES',
      },
      {
        unit: { kind: 'cross-cutting', dir: '' },
        state: {
          kind: 'partially-refreshed',
          refreshed: ['decision-markers.md'],
          stale: ['publication-gate.md'],
        },
        error: 'ENOENT',
      },
      {
        unit: { kind: 'provider', subdir: 'tracker/probe-provider' },
        state: { kind: 'restore-failed', recoveryPath: '/refs/tracker/probe-provider.old', restoreError: 'EIO' },
        error: 'ENOENT',
      },
    ];

    const messages = formatOverlaySummary({ overlaidRefs: [], overlayFailures: failures })
      .map(l => l.message);

    expect(messages).toHaveLength(4);
    expect(new Set(messages).size, 'two states rendering one sentence is the original defect').toBe(4);
    expect(messages[0]).toContain('left unchanged');
    expect(messages[1]).toContain('tracker/probe-provider/comment.md');
    expect(messages[2]).toContain('publication-gate.md');
    expect(messages[2]).toContain('the cross-cutting document set');
    expect(messages[3]).toContain('/refs/tracker/probe-provider.old');
    // Only the installed-unchanged state may make the 'left unchanged' claim.
    expect(messages.filter(m => m.includes('left unchanged'))).toHaveLength(1);
  });
});

// ---------------------------------------------------------------------------
// Known-bad probes for the path-keyed prune collector
// ---------------------------------------------------------------------------

describe('sweepOrphanedReferences — path-keyed prune collector', () => {
  let root: string;

  beforeEach(async () => {
    root = await fs.mkdtemp(path.join(os.tmpdir(), 'devflow-refsweep-'));
  });

  afterEach(async () => {
    await fs.rm(root, { recursive: true, force: true });
  });

  it('known-bad probe: a seeded file outside the manifest is reported by the same collector', async () => {
    await fs.mkdir(path.join(root, 'github'), { recursive: true });
    await fs.writeFile(path.join(root, 'github', 'setup-task.md'), 'keep\n', 'utf-8');
    await fs.writeFile(path.join(root, 'github', 'smuggled.md'), 'drop\n', 'utf-8');

    const result = await sweepOrphanedReferences(root, new Set(['github/setup-task.md']));

    expect(result.removed).toEqual(['github/smuggled.md']);
    expect(result.scanned).toBeGreaterThan(0);
    expect(await exists(path.join(root, 'github', 'setup-task.md'))).toBe(true);
    expect(await exists(path.join(root, 'github', 'smuggled.md'))).toBe(false);
  });

  it('removes a whole directory no manifest path descends into, and never descends into a retained one', async () => {
    await fs.mkdir(path.join(root, 'github'), { recursive: true });
    await fs.mkdir(path.join(root, 'acme', 'nested'), { recursive: true });
    await fs.writeFile(path.join(root, 'github', 'setup-task.md'), 'keep\n', 'utf-8');
    await fs.writeFile(path.join(root, 'acme', 'nested', 'x.md'), 'drop\n', 'utf-8');

    const result = await sweepOrphanedReferences(root, new Set(['github/setup-task.md']));

    expect(result.removed).toEqual(['acme']);
    expect(await exists(path.join(root, 'acme'))).toBe(false);
    expect(await exists(path.join(root, 'github', 'setup-task.md'))).toBe(true);
    expect(result.failed).toEqual([]);
  });

  it('an absent root is a no-op, not an error (avoids PF-009)', async () => {
    const result = await sweepOrphanedReferences(path.join(root, 'nope'), new Set(['a.md']));
    expect(result).toEqual({ scanned: 0, removed: [], failed: [] });
  });

  // The descent bound is shared with the build's prune (scripts/build-mds.ts) and is
  // breached at `depth > MAX_REFERENCE_SWEEP_DEPTH`, counting the swept root as depth 0.
  // The pair below is a known-bad probe and its in-bounds twin: the same orphan beside
  // the same manifest path, one directory apart. A bound that returned quietly would
  // hand back a result indistinguishable from the converged one (avoids PF-018).
  const nested = (levels: number): string =>
    Array.from({ length: levels }, (_, i) => `d${i + 1}`).join('/');

  async function seedNested(levels: number): Promise<{ known: string; orphan: string }> {
    const dir = nested(levels);
    await fs.mkdir(path.join(root, dir), { recursive: true });
    await fs.writeFile(path.join(root, dir, 'keep.md'), 'keep\n', 'utf-8');
    await fs.writeFile(path.join(root, dir, 'smuggled.md'), 'drop\n', 'utf-8');
    return { known: `${dir}/keep.md`, orphan: `${dir}/smuggled.md` };
  }

  it('sweeps the deepest directory the shared bound permits', async () => {
    const { known, orphan } = await seedNested(MAX_REFERENCE_SWEEP_DEPTH);

    const result = await sweepOrphanedReferences(root, new Set([known]));

    expect(result.removed).toEqual([orphan]);
    expect(result.failed).toEqual([]);
    expect(await exists(path.join(root, orphan))).toBe(false);
    expect(await exists(path.join(root, known))).toBe(true);
  });

  it('known-bad probe: a descent past the bound is reported in failed, not silently truncated', async () => {
    const tooDeep = nested(MAX_REFERENCE_SWEEP_DEPTH + 1);
    const { known, orphan } = await seedNested(MAX_REFERENCE_SWEEP_DEPTH + 1);

    const result = await sweepOrphanedReferences(root, new Set([known]));

    // The subtree genuinely was not swept — the orphan under it survives...
    expect(result.removed).toEqual([]);
    expect(await exists(path.join(root, orphan))).toBe(true);
    // ...and the sweep says so, naming the unvisited directory and the bound it hit,
    // through the same channel the installer already renders (report.sweepFailures).
    expect(result.failed).toHaveLength(1);
    expect(result.failed[0].name).toBe(tooDeep);
    expect(String(result.failed[0].error)).toContain(tooDeep);
    expect(String(result.failed[0].error)).toContain(String(MAX_REFERENCE_SWEEP_DEPTH));
  });
});
