import { promises as fs } from 'fs';
import * as path from 'path';

export const AUTO_GENERATED_MARKER = 'devflow-learning: auto-generated';

/**
 * Scan a file for the auto-generated marker in its first 10 lines.
 */
async function hasAutoGeneratedMarker(filePath: string): Promise<boolean> {
  try {
    const content = await fs.readFile(filePath, 'utf-8');
    const head = content.split('\n').slice(0, 10).join('\n');
    return head.includes(AUTO_GENERATED_MARKER);
  } catch {
    return false;
  }
}

/**
 * Remove auto-generated self-learning skills from the Claude skills directory.
 *
 * Detection uses the `devflow-learning: auto-generated` marker in file frontmatter.
 * Only removes artifacts that have this marker — safe, no false positives.
 * Skips devflow-namespaced skills (devflow: prefix) — those are managed by the installer.
 *
 * Note: the .claude/commands/self-learning/ directory is removed by the migration step
 * that calls this function (purge-learning-pipeline-v1 step 5) before this function runs.
 * This function handles skills only.
 *
 * Returns the count and paths of removed artifacts.
 */
export async function cleanSelfLearningArtifacts(
  claudeDir: string,
): Promise<{ removed: number; paths: string[] }> {
  const removed: string[] = [];

  // Scan skills directory for non-prefixed dirs (self-learning skills don't have devflow: prefix)
  const skillsDir = path.join(claudeDir, 'skills');
  try {
    const skillEntries = await fs.readdir(skillsDir, { withFileTypes: true });
    for (const entry of skillEntries) {
      if (!entry.isDirectory()) continue;
      // Skip devflow-namespaced skills — those are managed by the installer
      if (entry.name.startsWith('devflow:')) continue;

      const skillFile = path.join(skillsDir, entry.name, 'SKILL.md');
      if (await hasAutoGeneratedMarker(skillFile)) {
        await fs.rm(path.join(skillsDir, entry.name), { recursive: true });
        removed.push(path.join(skillsDir, entry.name));
      }
    }
  } catch {
    // skills dir doesn't exist — nothing to clean
  }

  return { removed: removed.length, paths: removed };
}
