import { promises as fs } from 'fs';
import * as path from 'path';

export const AUTO_GENERATED_MARKER = 'devflow-learning: auto-generated';

/**
 * Scan a file for the auto-generated marker in its first 10 lines.
 */
async function hasAutoGeneratedMarker(filePath: string): Promise<boolean> {
  try {
    const content = await fs.readFile(filePath, 'utf-8');
    const head = content.split('\n').slice(0, 10).join('\n');
    return head.includes(AUTO_GENERATED_MARKER);
  } catch {
    return false;
  }
}

/**
 * Remove all self-learning artifacts (skills and commands) from the Claude directory.
 *
 * Detection uses the `devflow-learning: auto-generated` marker in file frontmatter.
 * Only removes artifacts that have this marker — safe, no false positives.
 *
 * Returns the count and paths of removed artifacts.
 */
export async function cleanSelfLearningArtifacts(
  claudeDir: string,
): Promise<{ removed: number; paths: string[] }> {
  const removed: string[] = [];

  // Scan skills directory for non-prefixed dirs (self-learning skills don't have devflow: prefix)
  const skillsDir = path.join(claudeDir, 'skills');
  try {
    const skillEntries = await fs.readdir(skillsDir, { withFileTypes: true });
    for (const entry of skillEntries) {
      if (!entry.isDirectory()) continue;
      // Skip devflow-namespaced skills — those are managed by the installer
      if (entry.name.startsWith('devflow:')) continue;

      const skillFile = path.join(skillsDir, entry.name, 'SKILL.md');
      if (await hasAutoGeneratedMarker(skillFile)) {
        await fs.rm(path.join(skillsDir, entry.name), { recursive: true });
        removed.push(path.join(skillsDir, entry.name));
      }
    }
  } catch {
    // skills dir doesn't exist — nothing to clean
  }

  // Scan self-learning commands directory
  const commandsDir = path.join(claudeDir, 'commands', 'self-learning');
  try {
    const cmdEntries = await fs.readdir(commandsDir, { withFileTypes: true });
    for (const entry of cmdEntries) {
      if (!entry.isFile() || !entry.name.endsWith('.md')) continue;

      const cmdFile = path.join(commandsDir, entry.name);
      if (await hasAutoGeneratedMarker(cmdFile)) {
        await fs.unlink(cmdFile);
        removed.push(cmdFile);
      }
    }

    // Remove empty self-learning dir
    const remaining = await fs.readdir(commandsDir);
    if (remaining.length === 0) {
      await fs.rmdir(commandsDir);
    }
  } catch {
    // commands/self-learning dir doesn't exist — nothing to clean
  }

  return { removed: removed.length, paths: removed };
}
