import { describe, it, expect } from 'vitest'
import { loadFile, extractSection } from './helpers'

// -------------------------------------------------------------------------
// Command surfaces — must reference decisions-index.cjs index
// -------------------------------------------------------------------------

describe('Command surfaces — decisions-index.cjs index invocation', () => {
  const surfaces: Array<[string, string]> = [
    ['plan.md', 'plugins/devflow-plan/commands/plan.md'],
    ['resolve.md', 'plugins/devflow-resolve/commands/resolve.md'],
    ['self-review.md', 'plugins/devflow-self-review/commands/self-review.md'],
    ['code-review.md', 'plugins/devflow-code-review/commands/code-review.md'],
    ['debug.md', 'plugins/devflow-debug/commands/debug.md'],
  ]

  for (const [label, relPath] of surfaces) {
    it(`${label} invokes decisions-index.cjs index with {worktree} placeholder`, () => {
      const content = loadFile(relPath)
      expect(content).toContain('decisions-index.cjs index "{worktree}"')
    })
  }
})

// -------------------------------------------------------------------------
// debug.md — decisions orchestrator-local, not fanned
// -------------------------------------------------------------------------

describe('debug.md — decisions is orchestrator-local, not fanned to Explore investigators', () => {
  it('debug.md contains DECISIONS_CONTEXT (orchestrator uses it)', () => {
    const content = loadFile('plugins/devflow-debug/commands/debug.md')
    expect(content).toContain('DECISIONS_CONTEXT')
  })

  it('debug.md Investigate phase does NOT pass DECISIONS_CONTEXT to Explore investigators', () => {
    const content = loadFile('plugins/devflow-debug/commands/debug.md')
    const phase3 = extractSection(content, 'Phase 3: Investigate', '### Phase 4')
    expect(phase3).not.toContain('DECISIONS_CONTEXT')
  })
})

// -------------------------------------------------------------------------
// DECISIONS_CONTEXT substitution template — single canonical form
// -------------------------------------------------------------------------

describe('DECISIONS_CONTEXT template — uses canonical {decisions_context} form without fallback', () => {
  const templateSurfaces: Array<[string, string]> = [
    ['plan.md', 'plugins/devflow-plan/commands/plan.md'],
    ['resolve.md', 'plugins/devflow-resolve/commands/resolve.md'],
    ['self-review.md', 'plugins/devflow-self-review/commands/self-review.md'],
    ['code-review.md', 'plugins/devflow-code-review/commands/code-review.md'],
  ]

  for (const [label, relPath] of templateSurfaces) {
    it(`${label} does not use the legacy quoted or prose-fallback forms`, () => {
      const content = loadFile(relPath)
      // Quoted fallback (Form A)
      expect(content).not.toContain(`{decisions_context or '(none)'}`)
      // Prose-descriptive fallback (Form B)
      expect(content).not.toMatch(/\{decisions index from[^}]+, or \(none\)\}/)
      expect(content).not.toMatch(/\{Phase \d+ decisions index, or \(none\)\}/)
    })
  }
})

// -------------------------------------------------------------------------
// Consumer agents — must load devflow:apply-decisions via Skill tool (invoke-only architecture)
// -------------------------------------------------------------------------

describe('Consumer agents — devflow:apply-decisions loaded via Skill tool', () => {
  const agents: Array<[string, string]> = [
    ['resolver.md', 'shared/agents/resolver.md'],
    ['designer.md', 'shared/agents/designer.md'],
    ['scrutinizer.md', 'shared/agents/scrutinizer.md'],
    ['reviewer.md', 'shared/agents/reviewer.md'],
  ]

  for (const [label, relPath] of agents) {
    it(`${label} loads devflow:apply-decisions via Skill tool in body`, () => {
      const content = loadFile(relPath)
      // invoke-only architecture: no frontmatter skills: block; skill loaded at runtime via Skill tool
      expect(content).toContain('Skill(skill="devflow:apply-decisions")')
    })
  }

  it('simplifier.md does NOT invoke devflow:apply-decisions (code-shape role, not quality gate)', () => {
    const content = loadFile('shared/agents/simplifier.md')
    // simplifier is a code-shape agent — it should not load apply-decisions anywhere
    expect(content).not.toContain('Skill(skill="devflow:apply-decisions")')
  })
})

// -------------------------------------------------------------------------
// DECISIONS_CONTEXT input description — canonical form across consumer agents
// -------------------------------------------------------------------------

describe('DECISIONS_CONTEXT input declaration — canonical form', () => {
  const CANONICAL_DESCRIPTION =
    '**DECISIONS_CONTEXT** (optional): Compact index of active ADR/PF entries for this worktree (generated by `decisions-index.cjs index`). `(none)` when absent. Use `devflow:apply-decisions` to Read full bodies on demand.'

  const consumerAgents: Array<[string, string]> = [
    ['resolver.md', 'shared/agents/resolver.md'],
    ['designer.md', 'shared/agents/designer.md'],
    ['scrutinizer.md', 'shared/agents/scrutinizer.md'],
    ['reviewer.md', 'shared/agents/reviewer.md'],
  ]

  for (const [label, relPath] of consumerAgents) {
    it(`${label} declares DECISIONS_CONTEXT with canonical description`, () => {
      const content = loadFile(relPath)
      expect(content).toContain(CANONICAL_DESCRIPTION)
    })
  }
})

// -------------------------------------------------------------------------
// DECISIONS_CONTEXT variable present in all consumer surfaces
// -------------------------------------------------------------------------

describe('DECISIONS_CONTEXT variable — present in all four command surfaces', () => {
  it('plan.md contains DECISIONS_CONTEXT', () => {
    expect(loadFile('plugins/devflow-plan/commands/plan.md')).toContain('DECISIONS_CONTEXT')
  })

  it('self-review.md contains DECISIONS_CONTEXT', () => {
    expect(loadFile('plugins/devflow-self-review/commands/self-review.md')).toContain('DECISIONS_CONTEXT')
  })

  it('code-review.md contains DECISIONS_CONTEXT', () => {
    expect(loadFile('plugins/devflow-code-review/commands/code-review.md')).toContain('DECISIONS_CONTEXT')
  })

  it('debug.md contains DECISIONS_CONTEXT', () => {
    expect(loadFile('plugins/devflow-debug/commands/debug.md')).toContain('DECISIONS_CONTEXT')
  })

  it('resolve.md contains DECISIONS_CONTEXT', () => {
    expect(loadFile('plugins/devflow-resolve/commands/resolve.md')).toContain('DECISIONS_CONTEXT')
  })
})

// -------------------------------------------------------------------------
// Reviewer agent — apply-decisions section references skill
// -------------------------------------------------------------------------

describe('reviewer.md — Apply Decisions section', () => {
  it('contains Apply Decisions section referencing devflow:apply-decisions', () => {
    const content = loadFile('shared/agents/reviewer.md')
    expect(content).toMatch(/## Apply Decisions|### Apply Decisions/)
    expect(content).toContain('devflow:apply-decisions')
  })
})

// -------------------------------------------------------------------------
// plan.md — decisions loading phase present
// -------------------------------------------------------------------------

describe('plan.md — decisions loading phase', () => {
  it('contains a decisions-loading step (load decisions index)', () => {
    const content = loadFile('plugins/devflow-plan/commands/plan.md')
    expect(content).toMatch(/[Ll]oad.*[Dd]ecisions|[Dd]ecisions.*[Ll]oad/i)
  })
})

// -------------------------------------------------------------------------
// code-review.md — decisions loading phase present
// -------------------------------------------------------------------------

describe('code-review.md — decisions loading phase', () => {
  it('contains a decisions-loading step', () => {
    const content = loadFile('plugins/devflow-code-review/commands/code-review.md')
    expect(content).toMatch(/[Ll]oad.*[Dd]ecisions|[Dd]ecisions.*[Ll]oad/i)
  })
})
